### ISSUE TITLE
bizarre error message when saving 0d array

### ISSUE THREAD

**Issue by marcocamma** [silx-kit/fabio#101]
Hi,

At some point a script I was using stopped with the message

``` "AttributeError:` 'EdfImage' object has no attribute 'filename' ```

This happened while I was using f.save(fname)

I tracked down the problem and it seems to be caused when the array is 0d as shown by the snippet below:

```
import numpy as np
import fabio
img = np.asarray(1)
f = fabio.edfimage.EdfImage(img)
f.save("/tmp/todelete.edf")
``` 

I understand that a 0d array is somewhat of a corner case (indeed it was not intended but a previous step of my script returned it because of a bug) but a more transparent error message would be very useful.
I am using fabio 0.4.0

thanks a lot for the great work !
marco

**Comment by vallsv** [comment]
Funny. Thanks for the feedback.

**Comment by vallsv** [comment]
Hi again. Here is the result with a coming patch. It will be applied on the master soon.

```
In [1]: import numpy as np
   ...: import fabio
   ...: img = np.asarray(1)
   ...: f = fabio.edfimage.EdfImage(img)

Exception: Data with empty shape is unsupported
```
