### ISSUE TITLE
There is no 32-bit windows wheel for 0.4.0 on pypi

### ISSUE THREAD

**Issue by jonwright** [silx-kit/fabio#112]
The packaging nightmare continues. 

It seems win32 is part of the appveyor suite and you have some wheels (for example):

https://ci.appveyor.com/project/ESRF/fabio/branch/master/job/axoo70jv7w4ueabh/artifacts

... also Christophe Gohlke is distributing it for you.  But "pip install fabio" fails on windows with 32-bit pythons as there is no wheel on pypi.

**Comment by kif** [comment]
I uploaded the file (python 2.7, windows 32bits)
