### ISSUE TITLE
please migrate to PyQT5

### ISSUE THREAD

**Issue by picca** [silx-kit/fabio#151]
Hello guyes, I am preparing the packaging of fabio, BUT it seems that the fabio viewer depends on PyQt4.

Debian decided to get rid of PyQT4 because QT4 is no more supported by the upstream.
So it seems to me difficult to upload a package which contain a PyQT4 dependency.

Is it possible to use the silx qt module in order to be PyQT5 compatible.

thanks

Fred

**Comment by vallsv** [comment]
Hi.

We was afraid of the cyclic dependency `fabio->silx->fabio`. But with optional dependency provided by setuptools, maybe we can have something which work.

@kif would prefer to drop fabio_viewer. Is it possible to package fabio without fabio_viewer?

**Comment by picca** [comment]
In that case maybe the best is to integrate fabio into silx ;)

yes we can remove the viewer.

I will not create the fabio-bin package for now, It will need a process of the new queue. So it necessitate some time before an upload into Debain. So I will keep the fabio-viewer for now and once uploaded and migrated into testing I will upload a version into new.

Except if you integrate fabio into silx :))

**Comment by vallsv** [comment]
We think about merging `fabio_viewer` into `silx`. But there is no plan to merge `fabio` into `silx`.

**Comment by picca** [comment]
ok so at the end we will endup with a fabio-bin pacakge with only one script :)

**Comment by vallsv** [comment]
Yes :-D Maybe

**Comment by picca** [comment]
Ar eyou aware of this project

https://pypi.python.org/pypi/QtPy/

**Comment by vallsv** [comment]
Yes. But last time i try there was missing things, especially on PySide.
And we try to avoid as much as possible dependencies.

**Comment by picca** [comment]
I know ;), less dependency but more code to maintain on your own ;)

Cheers

**Comment by vallsv** [comment]
Using unstable and unfinished project is also a nightmare, especially when you have old target like Debian 7. If you have to monkey-patch projects before using it, you better to manage it by yourself.

This said, the project looks much mature than one year before. But while it is still the same Qt API, we anyway don't have much to change in case.
