### ISSUE TITLE
[debian] Integration of the debian directory into the sources

### ISSUE THREAD

**Issue by picca** [silx-kit/fabio#159]
Idem pyFAI

**Comment by vallsv** [comment]
Hi Frederic. Would it be possible to be more explicit? I don't think i get the point.

**Comment by picca** [comment]
Hello I explain the problem in the pyFAI idem requeste.

Do you need more information

**Comment by picca** [comment]
Here some precision, I would like to add in a dedicated branch debian/master as explained here
http://dep.debian.net/deps/dep14/ the debian packaging for unstable.

Is it ok for you to create this branch, then I will provide a patch for this branch.
Or should I clone your repository and propose a PR with this new branch ?

**Comment by vallsv** [comment]
We can talk about it at the Silx meeting next Wednesday.

I understand it should contain both the source and the Debian packaging. I am afraid that it will be quite difficult to maintain, cause we are close to a rolling release project.

**Comment by picca** [comment]
what is problematic for me is that we maintain two versions of the packaging for Debian.
one on the Debian infrastructure (my repository under debian-science) and one that you maintain under the package directory.

Maybe we should just add the debian directory directly in the master branch just to be able to do some continuous build for debian unstable.

**Comment by kif** [comment]
On Mon, 11 Sep 2017 08:26:48 -0700
picca <notifications@github.com> wrote:

> what is problematic for me is that we maintain two versions of the packaging for Debian.
> one on the Debian infrastructure (my repository under debian-science) and one that you maintain under the package directory.
> 
> Maybe we should just add the debian directory directly in the master branch just to be able to do some continuous build for debian unstable.
> 
Then you can put your version in "debian10" as the target is expected to be debian10 and it will not build with debian 8 or 9 soonish.

Cheers,

**Comment by vallsv** [comment]
> Then you can put your version in "debian10"

That's a good idea. If it is possible it can be a first step to a convergence of the scripts.
