### ISSUE TITLE
List of formats ignored when generating HTML

### ISSUE THREAD

**Issue by PiRK** [silx-kit/fabio#164]
The csv-table is not generated in the HTML doc on silx.org. Maybe the python module `docutil` is missing.

https://github.com/silx-kit/fabio/blob/master/doc/source/getting_started.rst#list-of-file-formats-that-fabio-can-read-and-write
http://www.silx.org/doc/fabio/dev/getting_started.html#list-of-file-formats-that-fabio-can-read-and-write

**Comment by vallsv** [comment]
Pierre found that the compilation on `silx.org` site was using the previous repositiory of fabio (at github/kif). Now it is fixed.
