### ISSUE TITLE
Typo in fabioimage api, "DEFAULT_EXTENTIONS"

### ISSUE THREAD

**Issue by ronpandolfi** [silx-kit/fabio#174]
"DEFAULT_EXTENTIONS" is misspelled. Caused a bit of confusion when I wrote "DEFAULT_EXTENSIONS" and my fabioimage subclasses didn't work; there was no indication of the source of the error, besides the class not being loaded into during fabioformats.get_all_classes().

**Comment by vallsv** [comment]
Hi. Nice catch. Unfortunately it is now part of the API, then it will be a little more difficult to fix it. But for the fact there is no warn if you don't follow the API, it will be difficult to fix it :-)

ATW about `get_all_classes` i warn you that your typo is not responsible of the fact your class is not exposed. You have, at least to import the module containing your class, else the library can't know it exists.

Here you can see i have to import my `fooimage` module, else it is not exposed by `get_all_classes`:
```
In [1]: import fabio.fabioformats

In [2]: fabio.fabioformats.get_all_classes()
Out[2]: 
[fabio.edfimage.EdfImage,
[...]
 fabio.mpaimage.MpaImage]

In [3]: import fabio.fooimage

In [4]: fabio.fabioformats.get_all_classes()
Out[4]: 
[fabio.edfimage.EdfImage,
[...]
 fabio.mpaimage.MpaImage,
 fabio.fooimage.FooImage]
```

**Comment by vallsv** [comment]
Here is a fix for the typo https://github.com/silx-kit/fabio/pull/175

**Comment by ronpandolfi** [comment]
Actually, I think I also had to clear the cache for _get_extension_mapping with
```
fabioformats.__dict__['_extension_cache'] = None
```
before attempting `fabio.open`. Otherwise, new formats aren't identified by extension.

**Comment by vallsv** [comment]
We should be able to fix that too.

**Comment by vallsv** [comment]
Here is a patch #176.

BTW if you think it is useful for everybody to be able to read your format, you are welcome to provide a patch.

**Comment by vallsv** [comment]
Finally we think about reworking the codec registration using an explicit method. See #177. It is not for now, but just to say that it can change in the feature, and you should be impacted.

**Comment by ronpandolfi** [comment]
Thanks for your help!
