### ISSUE TITLE
[debian] the 0.6.0 sources from pypi contain plenty of windows end terminated files

### ISSUE THREAD

**Issue by picca** [silx-kit/fabio#187]
In fact when I open setup.py with emacs I have plenty of files with ^M at the end of each line

cheers

Frederic

**Comment by picca** [comment]
sorry this was the previous version which was wrong,now it is ok.

**Comment by vallsv** [comment]
Yes, there was a lot of string chars in the setup.py

**Comment by picca** [comment]
Hello, I did the mistake to upload the new 0.6.0 version from the 0.4.x one.
sorry
