### ISSUE TITLE
fabio can't open files with a # in the file path

### ISSUE THREAD

**Issue by jbhopkins** [silx-kit/fabio#212]
I use fabio in a software package I maintain, and one of my users just discovered that it can't open images where there is a '#' in the file path. Here's an example I just ran using the pilatus2M.tif file from the fabio test images. This was done tested in:
ipython 
fabio version 0.6.0 (installed via pip)
MacOS 10.13.3.
python 2.7.13 (enthought canopy distribution)

Example of error:
```
In [1]: import fabio

In [2]: pwd
Out[2]: u'/Users/jessehopkins/Desktop/test#1'

In [3]: ls
pilatus2M.tif

In [4]: fabio.open('/Users/jessehopkins/Desktop/test#1/pilatus2M.tif')
---------------------------------------------------------------------------
IOError                                   Traceback (most recent call last)
<ipython-input-4-d5a0b736375c> in <module>()
----> 1 fabio.open('/Users/jessehopkins/Desktop/test#1/pilatus2M.tif')

/Users/jessehopkins/Library/Enthought/Canopy/edm/envs/User/lib/python2.7/site-packages/fabio/openimage.pyc in openimage(filename, frame)
    134     else:
    135         logger.debug("Attempting to open %s" % (filename))
--> 136         obj = _openimage(filename)
    137         logger.debug("Attempting to read frame %s from %s with reader %s" % (frame, filename, obj.classname))
    138         obj = obj.read(obj.filename, frame)

/Users/jessehopkins/Library/Enthought/Canopy/edm/envs/User/lib/python2.7/site-packages/fabio/openimage.pyc in _openimage(filename)
    185     except IOError as error:
    186         logger.debug("%s: File probably does not exist", error)
--> 187         raise error
    188     else:
    189         imo = None

IOError: [Errno 2] No such file or directory: '/Users/jessehopkins/Desktop/test'
```

**Comment by vallsv** [comment]
Maybe it is interpreted as a URL...

But a sharp in a file name it not a common thing.

**Comment by vallsv** [comment]
Thanks for the feed back. Here is a patch.

I try to use `%23` instead of the sharp as a work around, but it is not working.
Then you will have to use the dev branch when it will be merge to have something working.

**Comment by jbhopkins** [comment]
Thanks for fixing it. Feel free to close the issue once you're satisfied with the fix. I'll wait until it shows up in an official release to test it. As you say, a '#' in a filename isn't very common.
