### ISSUE TITLE
Allow PosixPath type for filenames. 

### ISSUE THREAD

**Issue by stmudie** [silx-kit/fabio#215]
It would be useful to support pathlib Path objects (i.e., PosixPath) for filenames.

For Python 3 just changing:
### fabioutils.py
Changing:
```
StringTypes = (str, bytes)
```
to:
```
from pathlib import PosixPath
StringTypes = (str, bytes, PosixPath)
```
was enough in my very quick test. Not sure what would be involved for Python 2.

I can try creating a Pull Request if this is seen as useful.

**Comment by vallsv** [comment]
Hi.

I don't think there is any problem to patch fabio with this library, but your proposal is not the good one. I see interesting to have typed objects, but your proposal consider that everything is everything. It would be much better to only patch part of the code which expect a path. We could create a `PathTypes`.

BTW `StringTypes` should be removed, as it is a dup with six.

**Comment by stmudie** [comment]
Yes I agree that that wouldn't be the correct solution, it was just a quick check to see if anything else was involved with patching the library.

**Comment by vallsv** [comment]
Then, if you like, feel free to send a patch. As it will not break existing code, there is no problem, we can improve it another time if something is missing.
Else i can try to do something next week.
