### ISSUE TITLE
EDF: EDF_BinarySize, Size and compression issue

### ISSUE THREAD

**Issue by diorcety** [silx-kit/fabio#219]
There is certainly multiple issue:
First: Size field is used for reading the data, shouldn't be EDF_BinarySize?
Second: The size field is corrected only if Compression is defined and starting by NO. Souldn't be the size field is correct if there is no compression header or this one start by NO?

**Comment by kif** [comment]
Hi Yann,

There has been a discussion in ~2010 whether we should support datablock compression in EDF. 
EDF being a chained list of (head+data) blocks, compressing will never allow fast access any frame.
We came out with the conviction that HDF5 was better suited for this. 

Today, many people do edf.gz files , i.e. compression outside the file (and  fabio tries to support them). but the "marginal" support for compressed datablock is completely unofficial and unsupported.
I am not very surprised there are issues there.

Valentin did rewrite the EDF stuff recently. I will wait until he comes back to discuss with him about this.
Cheers,
J.

**Comment by vallsv** [comment]
Hi,

I would say, is there something official in EDF format? There is no specification at all, then it is really difficult to do anything. I have to work on Fabio few days, i will check this `EDF_BinarySize` status.

I don't remember in the code that the headers or the data can be compressed (inside compression), but i can be wrong.

**Comment by vallsv** [comment]
BTW if you have use case with source code and data, it is more easy to talk about. You try to create by yourself an EDF file?
