### ISSUE TITLE
Destructor issue on application close.

### ISSUE THREAD

**Issue by t20100** [silx-kit/fabio#220]
With python3, silx 0.7.0 on Debian8, opening an EDF file, browsing the tree view without viewing data and closing the application with the top-right X leads to this message:
```
$ silx view FILE.edf 
WARNING:silx.app.view:Module 'hdf5plugin' is not installed. It supports some hdf5 compressions. You can install it using "pip install hdf5plugin".
Exception ignored in: <bound method File.__del__ of <_io.FileIO name='FILE.edf' mode='rb'>>
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/fabio/fabioutils.py", line 457, in __del__
  File "/usr/lib/python3/dist-packages/fabio/fabioutils.py", line 461, in close
AttributeError: 'NoneType' object has no attribute 'close'
```

**Comment by vallsv** [comment]
Could you check the fabio version you are using?

**Comment by t20100** [comment]
It's with fabio 0.6.0

**Comment by vallsv** [comment]
That's again something impossible to fix. It is when the class `File` call it's super class `FileIO`. Which mean the super class was released before the instance... No idea who to fix that. We should uses of `__del__` definitely, it's inconsistent with Python programing.

Maybe the application have to clean up it's data models before closing.

**Comment by vallsv** [comment]
Is it reproducible BTW?

**Comment by t20100** [comment]
That looks to have been fixed by https://github.com/silx-kit/silx/pull/1904  and is outdated, closing.
