### ISSUE TITLE
pb opening tiff file using Fabio

### ISSUE THREAD

**Issue by gourrier** [silx-kit/fabio#232]
I rely on Fabio for file input but I regularly run into problems when reading tiff files. I attach an example below.
Q1: I don't really understand what the pb is here, the size does match...
Q2: it seems that PIL somehow modifies the output (the statistics of the loaded array doesn't match with this of the image loaded with ImageJ). What is done exactly when falling back onto PIL ? I use pillow 5.0.0

The test file can be downloaded from: https://www.dropbox.com/s/jcbd73shy7aascv/_0001_C1_DEJ_equal_0060.tif?dl=0

---
#using v 0.6.0 under python 2.7.14
import fabio

fname = 'D:/Temp/_0001_C1_DEJ_equal_0060.tif'

dataarr = fabio.openimage.openimage(fname).data

>>WARNING:fabio.TiffIO:Bogus StripByteCounts information
WARNING:fabio.tifimage:Unable to read h:\Dentin\ZoneModele_0001_C1_DEJ\ZoneModele_0001_C1_DEJ\Seuillage\MyTests\_0001_C1_DEJ_equal\_0001_C1_DEJ_equal_0060.tif with TiffIO due to could not broadcast input array from shape (17304000,3) into shape (8400,2060,3), trying PIL

**Comment by vallsv** [comment]
Hi. It looks like there is a problem somewhere with the RGB images.
I will check it deeply. Thanks for the feed back.

**Comment by vallsv** [comment]
Anyway it mean the data is read using PIL, not our library, then the result should be anyway fine, but looks to only conttain one of the 3 channels. Then there is a double bug :-)

**Comment by vallsv** [comment]
```
DEBUG:fabio.tifimage:Backtrace
Traceback (most recent call last):
  File "/workspace/valls/fabio.git/build/lib.linux-x86_64-2.7/fabio/tifimage.py", line 140, in read
    data = tiffIO.getData(0)
  File "/workspace/valls/fabio.git/build/lib.linux-x86_64-2.7/fabio/TiffIO.py", line 350, in getData
    return self._readImage(nImage, **kw)
  File "/workspace/valls/fabio.git/build/lib.linux-x86_64-2.7/fabio/TiffIO.py", line 690, in _readImage
    image[rowMin:rowMax + 1, ...] = readout
ValueError: could not broadcast input array from shape (173040,3) into shape (840,206,3)
```

**Comment by vallsv** [comment]
Then the problem of your image is it is a RGB image using a palette. Color are indexed using a LUT.

In your case the palette index was returned, which is maybe not what you expect.

I create a patch to fix 2 issues, one from our reader using TiffIO, the other one from our PIL reader. As result the output data will have 3 dim (2 for the image size, 1 for the channels).

```
array([[[162,   0, 181],
        [156,   0, 191],
        [146,   0, 210],
        ..., 
        [ 98,   0, 220],
        [ 64,   0, 181],
        [  0,   0,  22]],

       [[156,   0, 191],
        [143,   0, 212],
        [131,   0, 220],
        ..., 
        [101,   0, 220],
        [ 64,   0, 181],
        [  0,   0,  22]],

       [[148,   0, 206],
        [131,   0, 220],
        [122,   0, 227],
        ..., 
        [104,   0, 221],
        [ 61,   0, 178],
        [  0,   0,  22]],

       ..., 
       [[  0,   0,  22],
        [ 55,   0, 171],
        [246,  90,   0],
        ..., 
        [254, 115,   0],
        [218,  37,  31],
        [ 76,   0, 195]],

       [[  0,   0,  22],
        [ 61,   0, 178],
        [168,   0, 162],
        ..., 
        [210,  21,  53],
        [254, 113,   0],
        [ 79,   0, 199]],

       [[  0,   0,  30],
        [ 94,   0, 216],
        [162,   0, 181],
        ..., 
        [195,   0,  93],
        [253, 111,   0],
        [ 76,   0, 195]]])
```

I still have to check things with my colleges, but it is maybe not what you expect. 
If you expect the reach the value (grey scale image), you should not use a colormap. If you expect to have the RGB image, it will be fine.

**Comment by gourrier** [comment]
Thanks for looking into this so quickly, I'm happy to see I wasn't completely off... I'll fiddle around with the colormap on my side and will happily test your patches, just let me know when it's OK for you and how I can access it.

**Comment by vallsv** [comment]
@gourrier could we use your image in our continuous integration test cases?

I tried to create an equivalent image with gimp, but it looks like your image contains another specificity.

**Comment by vallsv** [comment]
@gourrier the patch is merged. We will have a minor release of fabio this week, then you should have it soon accessible with pypi. But if you like to test it before, it's always welcome.

**Comment by gourrier** [comment]
@vallsv with some delay: yes (for using the image) and thanks !
