### ISSUE TITLE
PilatusImage headers. 

### ISSUE THREAD

**Issue by kif** [silx-kit/fabio#242]
In Python 3.7, PilatusImage headers are incorrectly parsed regardless if Pillow is installed or not.
Same bug on Windows and MacOS

**Comment by kif** [comment]
the bug is in regular expression parsing:
a = re.compile("\s*(?:[,:=]\s*)?")
a.split("a e",1) 
>>> "", "a e"

**Comment by serhiy-storchaka** [comment]
This is because re.split() supports splitting on empty strings in Python 3.7. Python 3.5 and Python 3.6 raised a warning for this code.

The regular expression `r"\s*[,:=\s]\s*"` works on all versions.
