### ISSUE TITLE
unusual-interpreter #!python#

### ISSUE THREAD

**Issue by picca** [silx-kit/fabio#250]
Hello,

while preparing 0.7.0 I got this error message

W: python3-fabio: unusual-interpreter usr/lib/python3/dist-packages/fabio/HiPiCimage.py #!python#
W: python-fabio: unusual-interpreter usr/lib/python2.7/dist-packages/fabio/HiPiCimage.py #!python#

**Comment by vallsv** [comment]
Hi Fred. Thanks for the feedback. It looks to be a typo.
It will be fixed today on the master.
