### ISSUE TITLE
python 3.8 deprecation messages

### ISSUE THREAD

**Issue by picca** [silx-kit/fabio#252]
For info, I get these messages when compiling fabio 0.7.0

/usr/lib/python3/dist-packages/pkg_resources/_vendor/pyparsing.py:943: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
  collections.MutableMapping.register(ParseResults)
/usr/lib/python3/dist-packages/pkg_resources/_vendor/pyparsing.py:3226: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
  elif isinstance( exprs, collections.Iterable ):
/usr/lib/python3.7/importlib/_bootstrap_external.py:434: ImportWarning: Not importing directory /usr/lib/python3/dist-packages/sphinxcontrib: missing __init__
  _warnings.warn(msg.format(portions[0]), ImportWarning)
/usr/lib/python3/dist-packages/setuptools/depends.py:2: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp

**Comment by vallsv** [comment]
Yes, we enabled all the warnings by default now.

But here it is about standard API or third party libraries. Then we can't do much.

**Comment by picca** [comment]
Sorry I did not saw that it was third party...

Cheers

**Comment by vallsv** [comment]
`pkg_resources` and `setuptools` could be fixed by ourself. I dont know for `importlib`.

**Comment by vallsv** [comment]
BTW, all the warnings are only enabled for unittests (and maybe the bootstrap). But not for the application.
