### ISSUE TITLE
pb saving array with dtype (u)int8 with tifimage

### ISSUE THREAD

**Issue by gourrier** [silx-kit/fabio#255]
Hi guys,

I'm trying to open an image, binarize it using skimage and saving the binerized data using tifimage but I have trouble saving the image in np.int8 or np.uint8 with tifimage, any idea why or how to correct this ?

code snipet:
```
import numpy as np
import fabio as _fabio
import skimage

fname = 'C:/Temp/1_232-2009 L_Z=50mm.tif'
dataarr = fabio.openimage.openimage(self.filename).data
#skimage returns a boolean array, need to convert to int something
binarr = skimage.filters.apply_hysteresis_threshold(dataarr, 10., 70.).astype(dataarr.dtype)
print binarr.dtype, binarr.sum()  #yields: uint8 4354845
outfname = 'C:/Temp/1_232-2009 L_Z=50mm_bin.tif'
img =fabio.tifimage.tifimage(binarr)
img.write(outfname)
```

This results in the correct type of output (as far as I can tell [i.e. only know it's 8 bits, but not sure whether signed or unsigned]) and the sum of the array tells me that I indeed have a number of pixels set to 1, but the resulting saved image is blank (i.e. all values set to 0).

I get the same behavior by setting explicitely np.int8, np.uint8 in astype. If I set np.int16 or np.int (32), then I get the correct expected output image (see C:/Temp/1_232-2009 L_Z=50mm_bin-1.tif) with a crazy image size, of course.

Is this a bug or am I missing something important in the use of tifimage (could spot anything in readthedocs) ?

The input/output data can be found at:
https://www.dropbox.com/sh/bwgequpl7l6fbbs/AAClc4y6qRvdPCoPp7_OBogUa?dl=0

**Comment by kif** [comment]
Hi Aurelien,

I checked your code, and it works for me (tested on debian9, python2.7)
Could you run this simple test case:
```
import numpy, fabio
print(fabio.version)
a=numpy.arange(100).reshape((10,10)).astype("int8")
f=fabio.tifimage.TifImage(data=a)
f.write("bug225.tiff")
```

By the way, is your fabio up-to date ? It is likely Valentin fixed it.
Jerome

**Comment by vallsv** [comment]
It also could be a bug due to different versions of skimage.

**Comment by vallsv** [comment]
Here is my test. As Jerome, i see nothing wrong with the master.

Which version of PyFAI do you use? PIL? skimage?

```
In [15]: def compute(filename):
    ...:     import fabio
    ...:     import skimage
    ...:     import skimage.filters
    ...:     dataarr = fabio.openimage.openimage(filename).data
    ...:     # skimage returns a boolean array, need to convert to int something
    ...:     binarr = skimage.filters.apply_hysteresis_threshold(dataarr, 10., 70.).astype(dataarr.dtype)
    ...:     print(binarr.dtype, binarr.sum())  # yields: uint8 4354845
    ...:     outfname = filename + '_output.tif'
    ...:     img = fabio.tifimage.tifimage(binarr)
    ...:     print("Result", binarr.min(), binarr.max())
    ...:     img.write(outfname)
    ...:    
    ...:     stored = fabio.open(outfname).data
    ...:     print("Stored", stored.min(), stored.max())
    ...:     print((stored == binarr).all())
    ...:     
    ...:     

In [16]: compute("../data/tiff/fabio_issue_255/1_232-2009 L_Z=50mm.tif")
uint8 362288
Result 0 1
Stored 0 1
True
```
