### ISSUE TITLE
Bug in Bruker100

### ISSUE THREAD

**Issue by kif** [silx-kit/fabio#281]
Under certain circumstances, self.ar_underflows can be undefined ...
Reported by email by Megan Forshey

**Comment by vallsv** [comment]
`self.ar_underflows = ar` is never reachable, as the loop with `k == 0` is skipped from the start.

**Comment by vallsv** [comment]
I also notice strange thing in the header:

```
  "LOWTEMP": "1  3010       -1500      TEMP: 300.00 6.0000 0", 
```
which should maybe stored as
```
  "LOWTEMP": "1  3010       -1500"
  "TEMP":    "300.00 6.0000 0"
```
But i don't know
