### ISSUE TITLE
Breaking changes for fabian...

### ISSUE THREAD

**Issue by jonwright** [silx-kit/fabio#295]
I just tested master against fabian (https://github.com/FABLE-3DXRD/fabian) and an issue came up with the dim1/dim2 business:

```
  File "C:\miniconda3\envs\py36_64\lib\site-packages\Fabian\appWin.py", line 1936, in openimage
    (img.dim2, img.dim1) = img.data.shape
AttributeError: can't set attribute
```
I get no warnings with 0.8.0 from pypi but the code fails in master. Seems the deprecation warning is not giving people time to fix their code?

**Comment by vallsv** [comment]
If img is a `FabioImage`, `img.dim1` and `img.dim2` are already equal to `img.data.shape` (that's an alias), then i guess this line is useless.

We could add a setter temporary for compatibility, that will not complain if the value is still the same.

The line `img.pilimage = None` could also be removed, are there is no more `pilimage` cached on `FabioImage`.

Thanks for the check, let me know if you want a PR on your project.

**Comment by vallsv** [comment]
> Seems the deprecation warning is not giving people time to fix their code?

No, in this case, there was no deprecation. It is mostly impossible to change anything without breaking stuffs. Without tests on this properties, I did not expect people to edit the size of the image, as it is obviously the size of the embed numpy array.

**Comment by vallsv** [comment]
Oh, in fact, `img.pilimage = None` will fail as `pilimage` is a property in read only (an alias to `toPIL16`).

In case of `= None` we also could add a temporary setter to avoid complains.

**Comment by vallsv** [comment]
Ok, I will create a PR for fabian with a cleaner code, and create deprecated setters in fabio (when it do not change the existing values, else an exception, cause i can't deal with it).

**Comment by vallsv** [comment]
Merge PR #298 would fix this problems.
Compatibility code was added.
