### ISSUE TITLE
Rigaku's new Hypix detector

### ISSUE THREAD

**Issue by stevestayrook** [silx-kit/fabio#299]
I would like to request that this image type be added.  I have attached an image for your examination.  The format of this image is d*TREK with an ACSII header.  The files can be read using ADXV, but neither RAW nor fabio can open these files.  Here is more information for you:

```
HEADER_BYTES= 5632;
BYTE_ORDER=little_endian;
PXD_DETECTOR_ACQUISITION_BIT_SHIFT=31 0;
PXD_DETECTOR_ACQUISITION_DATAMODE=Combined 31bit;
PXD_DETECTOR_DESCRIPTION=HyPix-3000;
PXD_DETECTOR_DIMENSIONS=775 385;
PXD_UNBINNED_BEAM_POSITION=677.6 190.5;
```

If you need more information, I would suggest contacting:  Angela.Criswell@rigaku.edu
Thanks,
Steve
[HSA_1_5mg_C1_0004.img.gz](https://github.com/silx-kit/fabio/files/2967687/HSA_1_5mg_C1_0004.img.gz)

**Comment by vallsv** [comment]
Thanks for the feedback.
In case, can we store this image in our unittest repository?

**Comment by vallsv** [comment]
I did small checks.
This format is quite similar to the ADSC format (same file extension, mostly the same header). But the binary data from d*TREK is more flexibility. As result it can't be parsed yet.

This would require some refactoring.

**Comment by jonwright** [comment]
Hi Vallentin, 

It looks like adscimage.py:_readheader is stopping on the curly brace in the header:

> {
> HEADER_BYTES= 5632;
> ASC_SAMPLE_HOLDER_NAMES={ Z X Y };
> 


...rather than reading HEADER_BYTES of data. The "SMV" format mentioned here also starts with HEADER_BYTES:
https://strucbio.biologie.uni-konstanz.de/ccp4wiki/index.php/SMV_file_format

Presumably it should try to read HEADER_BYTES if it finds that entry instead of stopping? Then split on the ";" and "=".

**Comment by vallsv** [comment]
My small fix matches `line == ')\n'` for the end of the block, instead of `'}' in line`.

But using `HEADER_BYTES` should be better.

And it would be better to use a dedicated reader for this format.

**Comment by jonwright** [comment]
There is C code here for comparison:
https://github.com/yayahjb/cbflib/blob/master/examples/adscimg2cbf.c
It reads a 512 byte block and looks for HEADER_BYTES. Seems to be a bug that it was stopping on the brace instead of reading the header size.

**Comment by vallsv** [comment]
Yes :-) this C code or our code have the same problem.

My check with `line == ')\n'` is maybe too strong, I suppose a file generated from Windows will contain `\r`?

**Comment by stevestayrook** [comment]
Yes, you may do with this image whatever is necessary.

Thanks,

Steve

On 03/15/2019 05:24 AM, Valentin Valls wrote:

Thanks for the feedback.
In case, can we store this image in our unittest repository?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://nam05.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fsilx-kit%2Ffabio%2Fissues%2F299%23issuecomment-473215156&data=02%7C01%7Csteve.stayrook%40yale.edu%7Cc0771a8230e64b225cd408d6a927f6c6%7Cdd8cbebb21394df8b4114e3e87abeb5c%7C0%7C0%7C636882386448677316&sdata=q8jeMrTTQmbowqoEIpj058Nn9dRE9tN4S%2BiOO4c9%2Fnw%3D&reserved=0>, or mute the thread<https://nam05.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAuSNCEL_7p5z0JZIKkENcL78rRsgXZOyks5vW2axgaJpZM4b0z5d&data=02%7C01%7Csteve.stayrook%40yale.edu%7Cc0771a8230e64b225cd408d6a927f6c6%7Cdd8cbebb21394df8b4114e3e87abeb5c%7C0%7C1%7C636882386448687321&sdata=ZNSUkZ51O%2FF4QrENyLEDH9M%2FlcTmQG58e8yihWMkP60%3D&reserved=0>.


--
Yale SCHOOL OF MEDICINE

Steven E. Stayrook, Ph.D.
Senior Research Scientist
Department of Pharmacology

Yale Cancer Biology Institute
Yale University - West Campus
ABC 109C, 840 West Campus Drive
West Haven, CT  06516

Yale University School of Medicine
New Haven, CT.  06520

phone: (203) 737-3833
cell:  (610) 787-2441
email:  steve.stayrook@yale.edu<mailto:steve.stayrook@yale.edu>

**Comment by vallsv** [comment]
Here is a cleaner PR #303 in case you like to test.

**Comment by vallsv** [comment]
Here is the result. I was afraid by the noisy pattern at the right of the image, but that's maybe normal.

![Screenshot from 2019-03-18 14-36-33](https://user-images.githubusercontent.com/7579321/54534568-ece21780-498c-11e9-8ed3-03233895bc6e.png)

**Comment by stevestayrook** [comment]
Yes, that is just noise.  I intend to mask out that region.  Is this then complete?  I will need to get in touch with the BioXTAS RAW board to support this format in their software.  Thank you for your great work.  Steve
