### ISSUE TITLE
[test] Find a HiPic sample for coverage

### ISSUE THREAD

**Issue by vallsv** [silx-kit/fabio#304]
That's HiPic file format from Hamamatsu CCD cameras.

There is no test relative to it.

**Comment by osholm** [comment]
Hi Valentin,

I have some data from Hamamatsu CCD cameras from Spring-8, I can give you for testing.

Cheers,
Henning

**Comment by kif** [comment]
Hi Henning
You can zip the file and upload it here ... We will build a non regression test based on it.
Cheers,

Jerome

**Comment by osholm** [comment]
Hi Jerome, 

Yes I can find one. I will just look around in my archives to see if I can find one that is more interesting than we ones I have readily available. These radiographies in a "zoom" setting, so they don't show a recognisable structure. 

I will be back shortly.

Henning

**Comment by kif** [comment]
Thanks, I made the file available for the test suite in:
http://www.silx.org/pub/fabio/testimages/Radiograph_SP8_BL47XU_HiPicimage.img.bz2
Writing the test should just be a formality.
