### ISSUE TITLE
Disable numpy allow_pickle

### ISSUE THREAD

**Issue by vallsv** [silx-kit/fabio#316]
It would be good to disable `allow_pickle=True` in the module numpy image as it is creating vulnerability issues.

https://github.com/numpy/numpy/blob/master/numpy/lib/npyio.py#L316

Test was failing (#313) cause the result of `fabioconvert` was generating numpy images containing pickle data. The PR #314 was fixing the tests. But it is maybe possible to avoid the issue, and to store a single image, or standard types (if supported), instead of pickled objects.

The content of this file should be anyway checked.

**Comment by picca** [comment]
Hello, I just activated the Salsa-CI and the autopkgtests for Debian, and it fails with thie error.

```
======================================================================
ERROR: testFullFormatName (fabio.test.testfabioconvert.TestFabioConvert)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/fabio/test/testfabioconvert.py", line 135, in testFullFormatName
    image = fabio.open("output/03.npy")
  File "/usr/lib/python3/dist-packages/fabio/openimage.py", line 159, in openimage
    obj = obj.read(obj.filename, frame)
  File "/usr/lib/python3/dist-packages/fabio/numpyimage.py", line 161, in read
    self.dataset = numpy.load(infile)
  File "/usr/lib/python3/dist-packages/numpy/lib/npyio.py", line 447, in load
    pickle_kwargs=pickle_kwargs)
  File "/usr/lib/python3/dist-packages/numpy/lib/format.py", line 696, in read_array
    raise ValueError("Object arrays cannot be loaded when "
ValueError: Object arrays cannot be loaded when allow_pickle=False
```

**Comment by kif** [comment]
On Sat, 19 Oct 2019 02:29:46 -0700
picca <notifications@github.com> wrote:

> Hello, I just activated the Salsa-CI and the autopkgtests for Debian, and it fails with thie error.

It has been addressed recenly ...

https://github.com/silx-kit/fabio/commit/ec7a2d124e337cccd2b1f1fb8b2b8f7f08ffcba5
