### ISSUE TITLE
Replace write(numpy.tostring) with numpy.tofile when writing file

### ISSUE THREAD

**Issue by jonwright** [silx-kit/fabio#325]
Following up on #323 there is a second temporary created when writing a file. 

The changes would  be more significant so I open this issue to see what you all think. You would need to replace code like:
```  
    file_object.write( data.tostring() )
```
...with a check to see it is really a file and not a compressed stream, then:
```  
    if isinstance( file_object, file ): 
        data.tofile( file_object )
    else:
        file_object.write( data.tostring() )
```
It would mean a bit of refactoring. The performance impact is easily measurable on linux as well as windows:
```
In [15]: f = open("NUL", "wb")   # /dev/null on linux

In [16]: %timeit [frame.tofile(f) for frame in t]
85 µs ± 134 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)

In [17]: %timeit [f.write(frame.tostring()) for frame in t]
36.2 ms ± 624 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
```
This was found as one of the top scores in a profile trace of PolyXSim.

**Comment by kif** [comment]
Hi Jon,
I made a quick benchmark under linux and found `/dev/null` was causing a strong bias in the result. On a ramdisk I got (2kx2k double array):
6.5ms tobytes/tostring
14ms tofile
19ms write(tobytes)

The figures with /dev/null would be in the order of 4 terabytes/s which is rather unrealistic.
Saving 25% of the time on this IO operation is worth.
