### ISSUE TITLE
openimage(FilenameObject) broken in 0.10.0 on github

### ISSUE THREAD

**Issue by jonwright** [silx-kit/fabio#370]
fabioutils.FilenameObject has a tostring() method but not a tobytes() method. I would be tempted to revert the edit in openimage, but the bytes/string story is not an area I can really help with. If you have unicode filenames then open probably need a string argument??

This broke very recently so I am a bit surprised to find it in the 0.10.0 release file from github.
```
Traceback (most recent call last):
  File "/home/esrf/wright/miniconda3power9/envs/pow37/lib/python3.7/site-packages/fabio/openimage.py", line 151, in openimage
    logger.debug("Attempting to open %s" % (filename.tobytes()))
AttributeError: 'FilenameObject' object has no attribute 'tobytes'
```

**Comment by kif** [comment]
mea culpa ... I'll propose a PR.
