### ISSUE TITLE
Read error on non-ascii characters for edf headers

### ISSUE THREAD

**Issue by jonwright** [silx-kit/fabio#373]
I found an edf image with some bad bytes (0xcd) padding the header. It was written by an old windows device server so probably was unititialized memory. I cannot them read with fabio (0.9.0 or 0.10.0). Not sure when it stopped working but we could read them in the past. Here is a stripped testcase:
```
>>> import fabio
>>> fabio.edfimage.edfimage( numpy.zeros((20,24), numpy.uint16) ).write("/tmp/test.edf")
>>> f=bytearray(open("/tmp/test.edf","rb").read())
>>> f[512-20]=0xcd                                          # mimic my bad data
>>> open("/tmp/testbad.edf","wb").write(f)
>>> fabio.open("/tmp/testbad.edf")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3/dist-packages/fabio/openimage.py", line 159, in openimage
    obj = obj.read(obj.filename, frame)
  File "/usr/lib/python3/dist-packages/fabio/edfimage.py", line 788, in read
    raise e
  File "/usr/lib/python3/dist-packages/fabio/edfimage.py", line 778, in read
    self._readheader(infile)
  File "/usr/lib/python3/dist-packages/fabio/edfimage.py", line 722, in _readheader
    block = self._read_header_block(infile, len(self._frames))
  File "/usr/lib/python3/dist-packages/fabio/edfimage.py", line 702, in _read_header_block
    return block[begin_block:end_block].decode("ASCII")
UnicodeDecodeError: 'ascii' codec can't decode byte 0xcd in position 491: ordinal not in range(128)

```
The real frames are in rnice:/data/id11/3dxrd/inhouse/jon/mar10/fe3o4_tomo_a_/

Sadly I am out of my depth with python strings. One option seems to be more forgiving:
`    return block[begin_block:end_block].decode("ASCII" , errors='replace') `
... but then I guess you corrupt strings when people have stored filenames in headers. In that case I guess someone might want bytes without any decoding and go figure it out themselves. So just delimit start and end with "{" and "}" and then split on ";" and "=".

Somewhat related. I still didn't figure out how run individual testcases, only the whole suite and then the testdata disappear. Maybe another issue for that?

**Comment by vallsv** [comment]
The `replace` option is supposed to be consistent when you encode/decode the stuff. It uses special unicode characters designed for (i think it was not the case in python2). So that's the way to go. If the content is dirty it will anyway stay dirty, but it least you could manually fix stuffs. Anyway it have to be robust.

For testcase you can specify the module, the class, the method
```
./run_tests.py package.package.module.ClassName.testMethod
```

**Comment by vallsv** [comment]
Hmmm, it looks like a i am wrong for the replace, i have to refresh my knowledge. Else it exists replace with espace sequences (`backslashreplace`), but i am pretty sure there is something with a unicode range of reserved characters.

**Comment by vallsv** [comment]
That's `surrogateescape`.
```
In [31]: b"\x30\x80\xF0\xF1".decode("ascii", "surrogateescape")                                                                         
Out[31]: '0\udc80\udcf0\udcf1'
```
I think that's a good solution. It will fail if you try to encode it back (without specifying it again in the `encode`). So most of the code will fail at write, but i think it's a good think, it force you to fix your file, but allow you to read it.

**Comment by jonwright** [comment]
That sounded good but I ran into a few problems:

- I don't find surrogateescape for python2 (for backporting)
- fixing encoding errors seems very hard? 

Based on a quick look and I find lines saying `decode("ascii")` in many header format interpreters.  Is there a reason not to just keep a bytes object when string decoding fails? I guess I can try to do that to learn more about python3.

Thanks for the tip for run_tests.py. I learned I can set FABIO_DATA to a local folder to work offline for testing too.

**Comment by vallsv** [comment]
Fabio do not support python2 anymore so, you really should upgrade.

**Comment by jonwright** [comment]
Are you sure surrogateescape is the right answer for helping users to read binary files in python3? You would give the user a string type when their file did not contain an ascii string type (or it is corrupted):
```
>>> b=np.arange(1024).tobytes()  # or struct.pack, etc
>>> s=b.decode('ascii',errors='surrogateescape')
>>> np.fromstring(s)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
UnicodeEncodeError: 'utf-8' codec can't encode character '\udc80' in position 1024: surrogates not allowed
>>> np.fromstring(s.encode('ascii','surrogateescape')==b
True
```
The string forgets it's source encoding so I can't just do `bytes(s)` and get it back again, they need to learn that last line.

As I said, I am out of my depth with python strings. I had in mind that when something like this doesn't backport to 2.7 it means you have bytes instead of string. 

Does surrogateescape let you put emoji in headers? I don't see how you can do that without another file encoding that overrides ascii for edf headers.

**Comment by jonwright** [comment]
e.g: 😄  in a header is U+1F601 or utf-8 as \xF0\x9F\x98\x81 but it could be some other encoding.
```
>>> s=bytes((0xf0,0x9f,0x98,0x81))
>>> s.decode('utf-8')
'\U0001f601'
>>> s.decode('ascii','surrogateescape')
'\udcf0\udc9f\udc98\udc81'
>>> s.decode('ascii','surrogateescape').encode('utf-8')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
UnicodeEncodeError: 'utf-8' codec can't encode character '\udcf0' in position 0: surrogates not allowed
```
How should they get their smile back?

**Comment by vallsv** [comment]
If you decode with surrogate, you have to encode with surrogate. The point here is to be able to read dirty things. But to prevent to write dirty things. So yes, you can read the file but not white the file while you did not fix the problems manually, and i think it's nice.

**Comment by vallsv** [comment]
> Are you sure surrogateescape is the right answer for helping users to read binary files in python3?

So to be clear, no, i think it is the right answer to read dirty files.

**Comment by vallsv** [comment]
> Does surrogateescape let you put emoji in headers?

No, an emoji is not a valid ascii, and everything bigger than 0x80 is not an ascii. For EDF files, that's just not allowed cause only ascii is allowed. So in this case the file is dirty and have to be considered as dirty. The surrogate only allow you to still read the file.

So maybe i dont really understand what you want to do. What is your usecase here?
- You want to read corrupted files? YOu anyway will have to deal manually with them
- You want to read a file written with the wrong encoding? (which is in this POV a corrupted file)
- You want to store UTF8 as a standard specification?

This 3 cases could not have the same answer.

**Comment by jonwright** [comment]
Thanks for the feedback! My feeling is that there is never a right answer with fabio and edfimage, just many compromises that build on top of each other.

**Comment by vallsv** [comment]
BTW, here is what i noticed on your file:
```
In [1]: import logging; logging.getLogger("fabio.edfimage").setLevel(logging.DEBUG)                                                 
In [2]: import fabio; image = fabio.open("fe3o4_tomo_a__quantix_0227.edf")                                                          

DEBUG:fabio.edfimage:Non key-value line: b'4.7864'
DEBUG:fabio.edfimage:Non key-value line: b'8.7156'
DEBUG:fabio.edfimage:Non key-value line: b'\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd
\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd
\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd
\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd
\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd
\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd
\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd
\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd
\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd
\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd
\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd'
```
For now i display the logs as debug, but i really think it would be displayed as a warning. You can see that you have store values what will be lost (`4.7864`, `8.7156`), and the trailing value is still dirty, so the file should be sanitized antway.
