### ISSUE TITLE
version confusion

### ISSUE THREAD

**Issue by jonwright** [silx-kit/fabio#379]
My CI for ImageD11 is getting the fabio-v0.10.0 release from pip/pypi for python2.7. Since master started getting breaking changes can we add a Requires-Python please?
https://packaging.python.org/guides/dropping-older-python-versions/

**Comment by kif** [comment]
On Fri, 10 Apr 2020 05:57:11 -0700
Jon Wright <notifications@github.com> wrote:

> My CI for ImageD11 is getting the fabio-v0.10.0 release from pip/pypi for python2.7. Since master started getting breaking changes can we add a Requires-Python please?
> https://packaging.python.org/guides/dropping-older-python-versions/

Makes sense ... 
In the spirit of:
https://github.com/silx-kit/fabio/pull/369/commits/c1ec28e8ba7b35b6b569ec533006359becaf9be0
