### ISSUE TITLE
CBF write method allows filenames that are not compatible with fabio.open

### ISSUE THREAD

**Issue by jonwright** [silx-kit/fabio#388]
It seems the CBF format does not have a "magic" byte string at the top of the file to identify the file type. If the name is wrong, it is not recognised (see https://github.com/FABLE-3DXRD/ImageD11/issues/98).

```
>>> im = fabio.open("my_raw_data.cbf")
>>> im.data = processed(im.data)
>>> im.write( "my_fixed_data.edf" )
```
... the resulting file is not in edf format, but remains as a CBF, the type that was opened. I guess there needs to be some kind of check on the filename whenever the filename is in conflict with the file format. Or perhaps automatically add it if there is a required filename extension.

**Comment by kif** [comment]
On Tue, 12 May 2020 08:52:31 -0700
Jon Wright <notifications@github.com> wrote:

> It seems the CBF format does not have a "magic" byte string at the top of the file to identify the file type. If the name is wrong, it is not recognised (see https://github.com/FABLE-3DXRD/ImageD11/issues/98).
> 
> ```
> >>> im = fabio.open("my_raw_data.cbf")
> >>> im.data = processed(im.data)
> >>> im.write( "my_fixed_data.edf" )  
> ```
> ... the resulting file is not in edf format, but remains as a CBF, the type that was opened. I guess there needs to be some kind of check on the filename whenever the filename is in conflict with the file format. Or perhaps automatically add it if there is a required filename extension.

I don't think this is a bug ... The filename extension is not used to
select the format for saving (it has never been).
`im` is an "CbfImage" and remains a "CBFImage" after the assignment of the new data. If you want your data as EDF, you have to convert it:
```
im = fabio.open("my_raw_data.cbf")
cor = EdfImage(data= processed(im.data), header=im.header)
cor.write("my_fixed_data.edf") 
```

You can also see the "convert" method of FabioImage.

**Comment by jonwright** [comment]
I didn't see it as a "bug", just a user-friendliness issue. The write method in CBFimage.py is writing into filenames which fabio.openimage cannot read. It seems to come up with all the formats which do not have magic byte headers to identify file formats correctly, so I think a name check would be useful elsewhere.

Looking at international tables I see there is something missing for CBF specifically: https://it.iucr.org/Ga/ch2o3v0001/

> 2.3.3.1. Details of the magic number 
The magic number identifier is ###CBF: VERSION. This must always be present so that a program can easily identify a CBF by simply inputting the first 15 characters. [The space is a blank (ASCII 32) and not a tab. 

We should be able to get this to work independently of filenames for CBF. Nevertheless, there is a new generation of people who grew up using computers that hide the filename extensions from them. Renaming a jpeg to png does not change the format, but we could try to be more graceful in trying to cope with this kind of problem? I think software like word/excel add on the "right" extension for you when saving.

**Comment by vallsv** [comment]
Using the same object to read something, and to write something else is anyway a bad design. `.data` should be read only (like any other attributes) in order to avoid this kind of mistakes.

Maybe because the EDF reader do not fail anymore when we feed it with garbage, fabio is not anymore able to switch to the CBF parser. If that's the case, that's a really interesting issue.

**Comment by jonwright** [comment]
I was never aware of a try-fail-now-try-another format in fabio. Where does that happen? 

I thought it should be getting the magic bytes from the header and calling CBFimage directly. It is the same as the case of renaming a png file to a jpg without converting it. Some software tolerates this kind of problem, I thought fabio did. In the original openimage.py this would fail because I kept the names first for backwards compatibility. Magic was a fallback for names we didn't understand:

 https://sourceforge.net/p/fable/code/1592/tree/fabio/trunk/src/openimage.py#

At r1899 Henning decided to go over to trusting the file contents more than we trust the way people name the files, so put the magic codes first. There are some formats that cannot be guessed from names so this seemed essential. Cycling over formats seemed risky as we thought one might parse but give corrupted data (e.g. ADSC might parse as EDF but you should not mix them). The marccd versus tif was awful for this.

If you make something read only and create a new object the problem seems to remain:
```
>>> im = fabio.CBFImage(data=np.zeros((10,10), header=valid_cif_header) 
>>> im.write("renamed.edf")
>>> fabio.open("renamed.edf")
... barfs ?
``` 
If you mean read only to mean "stop writing CBF" then this seems like an over-reaction to the problem?!

**Comment by vallsv** [comment]
> I was never aware of a try-fail-now-try-another

It was just a guess, i did not checked anyway. But i remember try-except.

> I thought it should be getting the magic bytes from the header and calling CBFimage 

Yes it should. As far as i remember Fabio check the magic first and do other stuff around as fallback. So maybe there is a regression, maybe there is a bug, maybe it was working this way for a while. I have no idea without doing deep inside first.

```
>>> im = fabio.CBFImage(data=np.zeros((10,10), header=valid_cif_header) 
>>> im.write("renamed.edf")
```
I feel like you know explicitly that you are doing a mistake here.

> If you mean read only to mean "stop writing CBF" 

I was just talking about the class attributes. Nothing personal with that format :-)

**Comment by jonwright** [comment]
One goal with fabio was to be able to do `fabio.open(user_string)` and then put all of the file format problems in one place. It makes a really horrible place to maintain, but this had a huge benefit for a lot of other codes. One fix seems plausible but I think Jerome is the only one who knows the CBF code:

- `CBFimage.__version__` is changed to add magic bytes and these are registered for reading

Second would have a lot of impact:

- A parent fabioimage.write method is called which checks arguments before calling something like _write from the subclass. This could try to mimic pillow.image.save and matplotlib.pyplot.savefig behavior of looking at name extension to guess formats.

Historically we only cared about reading data. Writing and converting was viewed as too difficult except for the most simple formats. I always thought a format had the best chance to write correctly if there was no conversion, but this is because I was using edf.

**Comment by kif** [comment]
I agree to implement the first idea. I was not aware of those magic bytes. I'll send a PR soon.

For the second, it basically comes down to the translation of the metadata and the automatic conversion of file-formats for which we wrote something like:
```Automatic   translation between  file  formats,  even  if  desirable,  is  sometimes  impossible because  not  all  formats  have  the  capability  to  be  extended  with additional  metadata```

**Comment by kif** [comment]
As each format contains a hint for the associated file extensions, there could be a warning about saving data with an inconsistent extension.
