### ISSUE TITLE
Getting the next hdf5 frame ?

### ISSUE THREAD

**Issue by jonwright** [silx-kit/fabio#397]
Trying out Hdf5Image.next() it seems it returns a FabioFrame instead of a FabioImage. This does not have a "next" method for getting the N+1 and so on. Various options would "fix" it for me :
- change the "next" method within Hdf5Image to return something inheriting from FabioImage (as advertised)
- add a "next" method on Hdf5Frame
- have Hdf5Frame inherit from Hdf5Image (smallest change)

"next" seems to be well defined for slices into a 3D array. In the longer term I could try to abandon this "next" functionality, I am not sure if anyone else is using it anyway. Do you have any preference if I try to make a patch?

**Comment by vallsv** [comment]
This will also impact other format based on `FabioFrame`.

So implementing next to a frame sounds better.

The other proposals mixes concepts of what is about a file (FabioImage) and what is about a frame (FabioFrame). And i think that it's not a good idea.

But frankly, the `next` concept is not very pythonic. The iterator `image.frames()` is in all way better. Especially here where i think you don't have to deal with file series.

**Comment by vallsv** [comment]
Here is an implementation. Take a look at the unittest. You have to store the reference of the fabioimage on your side. Else the object will be released, and the current frame will not have anymore a next frame.
