### ISSUE TITLE
autopkgtest fail with the latest numpy

### ISSUE THREAD

**Issue by picca** [silx-kit/fabio#398]
Hello, I got this bug from Debian

```
Source: numpy, python-fabio
Control: found -1 numpy/1:1.19.0-1
Control: found -1 python-fabio/0.10.2+dfsg-1
Severity: serious
Tags: sid bullseye
X-Debbugs-CC: debian-ci@lists.debian.org
User: debian-ci@lists.debian.org
Usertags: breaks needs-update
```

Dear maintainer(s),

With a recent upload of numpy the autopkgtest of python-fabio fails in
testing when that autopkgtest is run with the binary packages of numpy
from unstable. It passes when run with only packages from testing. In
tabular form:
```
                       pass            fail
numpy                  from testing    1:1.19.0-1
python-fabio           from testing    0.10.2+dfsg-1
all others             from testing    from testing
```
I copied some of the output at the bottom of this report.

Currently this regression is blocking the migration of numpy to testing
[1]. Due to the nature of this issue, I filed this bug report against
both packages. Can you please investigate the situation and reassign the
bug to the right package?

More information about this bug and the reason for filing it can be found on
https://wiki.debian.org/ContinuousIntegration/RegressionEmailInformation

Paul

[1] https://qa.debian.org/excuses.php?package=numpy

https://ci.debian.net/data/autopkgtest/testing/amd64/p/python-fabio/6059874/log.gz

```
======================================================================
FAIL: test_linear (fabio.test.codecs.test_brukerimage.TestBrukerLinear)
test for self consistency of random data read/write
----------------------------------------------------------------------
Traceback (most recent call last):
  File
"/usr/lib/python3/dist-packages/fabio/test/codecs/test_brukerimage.py",
line 149, in test_linear
    self.assertTrue(error < numpy.finfo(numpy.float32).eps, "Error is
%s>1e-7" % error)
AssertionError: False is not true : Error is 0.99999905>1e-7

----------------------------------------------------------------------
Ran 324 tests in 330.792s

FAILED (failures=1, skipped=17)
```

**Comment by vallsv** [comment]
Hi Fred,
Jerome have fixed this issue in this PR #392. Is that enough to close your issue?
Regards,

**Comment by kif** [comment]
They want a new release ...

**Comment by vallsv** [comment]
They also can add patches on there side

**Comment by picca** [comment]
Hello, guyes.
I can add a patch, no problem

cheers

**Comment by kif** [comment]
thanks: we are busy restarting
