### ISSUE TITLE
Fragile TiffIO?

### ISSUE THREAD

**Issue by joelvbernier** [silx-kit/fabio#405]
Hello all --

I'm currently using fabio 0.10.2 and having an issue loading the attached tiffs.
```
WARNING:fabio.TiffIO:Bogus StripByteCounts information
WARNING:fabio.tifimage:Unable to read PXRDIP-s25818_IMAGE-PLATE-L.tif with TiffIO due to index 289 is out of bounds for axis 0 with size 256, trying PIL
ERROR:fabio.tifimage:Error in opening PXRDIP-s25818_IMAGE-PLATE-L.tif with PIL: cannot identify image file <_io.FileIO name='PXRDIP-s25818_IMAGE-PLATE-L.tif' mode='rb' closefd=True>
ERROR:fabio.tifimage:Error in opening PXRDIP-s25818_IMAGE-PLATE-L.tif: no tiff reader managed to read the file.
```
By contrast, imageio's tiff reader (via `skimage.io`) seems to load it fine.  FWIW the tiff was saved from ImageJ on Windows 10.

Thanks!
[PXRDIP-s25818_IMAGE-PLATES.zip](https://github.com/silx-kit/fabio/files/5337626/PXRDIP-s25818_IMAGE-PLATES.zip)

**Comment by kif** [comment]
This is possible. The best is to let @vasole  have a look.

**Comment by vasole** [comment]
More than fragile TiffIO, ImageJ that providing inconsistent information

![image](https://user-images.githubusercontent.com/5636251/95429489-c3138b80-094a-11eb-91fc-6e105f1f1b3e.png)

I will try to workaround the colormap information.

**Comment by vasole** [comment]
The PR should fix it but it is just a choice. One gets a colormap and a monochrome interpretation. One of the two is wrong.

The previous choice was that if one had bothered to provide a colormap it was to use it. Current choice is that a colormap will be ignored unless explicitly asked to use it (interpretation == 3)

**Comment by joelvbernier** [comment]
Thanks @vasole I will give this a try.  Unfortunately ImageJ tiffs are pervasive out there in the wild...
