### ISSUE TITLE
Tests fails with Python 3.9

### ISSUE THREAD

**Issue by t20100** [silx-kit/fabio#410]
Running the tests with Python 3.9 fails due to Python3.9 breaking backward compatibility of `bz2.BZ2File` API with python2:
```
======================================================================
ERROR: testFlat (fabio.test.test_fabio_image.TestOpen)
no compression
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/python/cp39-cp39/lib/python3.9/site-packages/fabio/test/test_fabio_image.py", line 149, in setUp
    with fabioutils.BZ2File(self.testfile + ".bz2", "wb") as wf:
  File "/opt/python/cp39-cp39/lib/python3.9/site-packages/fabio/fabioutils.py", line 606, in __init__
    bz2.BZ2File.__init__(self, name, mode, buffering, compresslevel)
TypeError: __init__() takes from 2 to 3 positional arguments but 5 were given
```
and many more.
See https://gitlab.esrf.fr/silx/bob/fabio/-/jobs/154479 for the full log.

Issue is here: https://github.com/silx-kit/fabio/blob/b57fee97c8693eb340525e3430f3f1c7f3a89b72/fabio/fabioutils.py#L606

[Python 3.8 doc](https://docs.python.org/3.8/library/bz2.html#bz2.BZ2File):
> class bz2.BZ2File(filename, mode='r', buffering=None, compresslevel=9)
> [...]
> The buffering argument is ignored. Its use is deprecated since Python 3.0.

[Python 3.9 doc](https://docs.python.org/3/library/bz2.html#bz2.BZ2File):
> class bz2.BZ2File(filename, mode='r', *, compresslevel=9)

**Comment by kif** [comment]
Changed in version 3.9: The buffering parameter has been removed. It was ignored and deprecated since Python 3.0. Pass an open file object to control how the file is opened.

I'll refactor this to drop the deprecated parameter.
