### ISSUE TITLE
CI is broken under windows 32 bits ...

### ISSUE THREAD

**Issue by kif** [silx-kit/fabio#414]
H5py does not exist there ... shall we drop windows 32 bits ?

**Comment by vallsv** [comment]
Is that a kind of question? ;-)

**Comment by kif** [comment]
I do not like working on windows OS, but I can understand that some setups require windows-32bits, because they are piloting a diffractometer with legacy hardware ... and the operator may be using FabIO for whatever reason.

If someone is in this case, this person is welcome to help us in providing the wheels to fix the C.I. unless I think I will drop win32 in the coming days, actually the next PR to merge.
