### ISSUE TITLE
mrc file is shifted

### ISSUE THREAD

**Issue by elena-pascal** [silx-kit/fabio#444]
Compared to the behaviour of `mrcfile`, using `fabio` gives me an mrc images that looks shifted to the right.

It looks like [this](https://github.com/elena-pascal/fabio_test/blob/main/fabio_mrc.ipynb)

Is there something I am missing?

**Comment by kif** [comment]
Hi,

There is clearly a bug in fabio while reading of the offset of the start of the image. 
Can you share those files to let us build a non regression test ?
I am not using MRC files myself ... but I can probably fix it.

Cheers

Jerome

**Comment by elena-pascal** [comment]
Hi Jerome, 

Thank you for quick response!
The problem file is [here.](https://github.com/elena-pascal/fabio_test/blob/main/0p67_5s_0000.mrc) 

Elena

**Comment by kif** [comment]
Hi Elena,

For what I can see, the offset is 768 bytes (192 values) ... 
Actually the extended header was not read ...

There is a PR to fix this issue.

Cheers,

Jerome
