### ISSUE TITLE
Outdated and obscure README

### ISSUE THREAD

**Issue by loichuder** [silx-kit/fabio#455]
Having tried to use fabio again after a few months, I found the README was not very helpful:
- It contains outdated information (e.g. the code snippet https://github.com/silx-kit/fabio#transparent-handling-of-compressed-files does not work for fabio 0.11.0)
- I also got the feeling that "Using fabio in your own python programs" was supposed to be a header ? :shrug: 
- The link to the "real" documentation is not visible. It could also be a direct link to the latest documentation.
- The section https://github.com/silx-kit/fabio#design-specifications is not very readable (could use some backtick formatting)
- Scrolling all the way down is not worth the effort as the Installation and Changelog sections only give links (which cannot even be followed)

If a maintainer agrees on these statements, I will be happy to submit a PR

**Comment by vallsv** [comment]
+1, what i think you care is a basic example to read and write something.
