### ISSUE TITLE
fabio.tifimage:Error in opening tiff file

### ISSUE THREAD

**Issue by agshabalin** [silx-kit/fabio#458]
Hello!

when opening a tiff file:
[test.zip](https://github.com/silx-kit/fabio/files/7347876/test.zip)
with a command:

> I = fabio.open('./test.tif')

I get the following error:

> WARNING:fabio.tifimage:Unable to read ./test.tif with TiffIO due to Only grayscale images supported, trying PIL
> ERROR:fabio.tifimage:Error in opening ./test.tif with PIL: cannot identify image file <_io.FileIO name='./test.tif' mode='rb' closefd=True>
> ERROR:fabio.tifimage:Error in opening ./test.tif: no tiff reader managed to read the file.

I was told that the problem is that this .tif was written using a newer ISO (from 2001) than the one used by fabio (from 1992). If in the .tif file I replace the following tag:

> PhotometricInterpretation PHOTOMETRIC.CFA

by:

> PhotometricInterpretation PHOTOMETRIC.MINISBLACK

then fabio can open it. However, it would be great to have a more sustainable solution, for example, if fabio can support .tif files of the newer standard.
Thank you!

**Comment by kif** [comment]
CFA ... do you expect the demosaicing to be automatic ?

**Comment by agshabalin** [comment]
> CFA ... do you expect the demosaicing to be automatic ?

I guess yes, if that would not affect reading other *tiff files.

**Comment by kif** [comment]
Since demosaicing depends on the type of Bayer pattern (several exists) and several algorithm exists ... not simple to replace a tool such as `rawtherapee`with something completely automatic...
https://github.com/Beep6581/RawTherapee

**Comment by agshabalin** [comment]
If it's hard to make it automatic maybe there are other solutions?
I work with software packages such as FABLE and HEXRD in which usage of fabio is hardcoded.
If fabio fails to read some tifs or requires providing some additional parameters,  then those packages would also fail.

**Comment by kif** [comment]
This issue has been fixed.
