### ISSUE TITLE
Misspelled CIF keyword in CBF header causes Eval15 not to recognize scan parameters from CBF header

### ISSUE THREAD

**Issue by RufusTFirefly** [silx-kit/fabio#471]
Hi FABIO developers

Something I noticed while using fabio to create CBF files from scratch, that is from an array of data and a text header.
I basically do the following (I know that it is a bit like "kicking the box" but it seems to work fine):

                image = fabio.cbfimage.CbfImage()
                image.data = counts
                image.shape = [ny,nx]
                image = image.convert("cbf")
                image.pilatus_headers = header
                image.save(cbffile)

where header is a plain text like:

    # Pixel_size 1.720000e-04 m x 1.720000e-04 m
    # Exposure_time 60.000000 s
    # Wavelength 0.560834 A
    # Detector_distance 0.040000 m
    # Start_angle -14.500000 deg.
    # Angle_increment 1.000000 deg.
    # Detector_2theta 23.240000 deg.
    # Phi 25.000000 deg.
    # Phi_increment 0.000000 deg.
    # Chi -20.000000 deg.
    # Omega -14.500000 deg.
    # Omega_increment 1.000000 deg.
    # Oscillation_axis OMEGA

The generated CBF file can be read with ALBULA. The counts are OK. When I then try to process the images with Eval15, the scan parameters (axes' positions, detector's distance etc), which are normally read from the header, appear to be all zero!
The problem is that the header is introduced with the CIF keyword "_array_data.header_content" which is wrong.
The correct CIF keyword should be "_array_data.header_contents".
The error is in file "cbfimage.py, line 329 (fabio 0.13.0):

            self.cif["_array_data.header_content"] = str(self.pilatus_headers)

Changing it to

            self.cif["_array_data.header_contents"] = str(self.pilatus_headers)

fixes the problem with the scans recognition. Notice that in several other places in the "cbfimage.py" file, the correct CIF keyword is used.

Best regards

RTF

**Comment by kif** [comment]
Thanks for the report,
can you submit a PR ?
