### ISSUE TITLE
How to convert .img file from ADSC detector to Bruker .sfrm format?

### ISSUE THREAD

**Issue by youthcould** [silx-kit/fabio#48]
Hi Kif,

Thanks for the great fabio project. Recently I got confusing of converting these frames collected by an ADSC detector to Bruker files. It is really a surprise when I found the fabio project.
It shows the .img file could be read by fabio and .sfrm file could be write by fabio. However, with the new fabio_viewer, it do have a choice to save as .sfrm file. However, this sfrm file can not be read by bruker apex II, can you help me about this. also, the automatic format recognition procedure seems didn't work correctly. Please help me

**Comment by youthcould** [comment]
btw, I am using windows 7 64bit

**Comment by jonwright** [comment]
Hello,

Converting to something APEX could read has been done in the past using 
the huber2bruker.py script which is in ImageD11. It writes SAXI format, 
not sfrm.

https://sourceforge.net/p/fable/code/HEAD/tree/ImageD11/trunk/scripts/huber2bruker.py

So far as I remember you needed to use: 3 digits for the file extension 
and numbers to start at 1.


Jon

**Comment by youthcould** [comment]
Hi Jon,
Thank you for your help. After spending several hours trying this, I still can not handle this as I don't know much about these python code. Can you give me more tips, or is there any compiled program with a UI interface which could do this.
Thank you very much.

**Comment by jonwright** [comment]
I made a quick test using a test image:

fabio/test/testimages % huber2bruker.py -n mb_LP_1_ -f 1 -l 2 -e .img 
--ndigits=3

-n = name of the images up to the number
-f = number of the first image (usually zero for us)
-l = number of the last image
-e = extension on the filenames, usually ".edf" for us, but it is .img 
for you
--ndigits = number of digits in the output filenames: you want 3 for 
APEX but we usually get 4 digits for smart/saint.

The input images were named:
     mb_LP_1_0001.img and mb_LP_1_0002.img
The output images were named:
     mb_LP_1__0.002 and mb_LP_1__0.003

Note: 4 digits were needed in the input filenames (it can be changed).

No attempt is made to transfer the header information (ADSC is typically 
incorrect as they sell detectors but not diffractometers).

To get it working for you may need some more work, depending on what the 
bruker software allows you to do about header information which is 
missing or incorrect.

I can make a simplified version of huber2bruker.py for you but I don't 
have APEX to be able to test it ....

Best

Jon

**Comment by youthcould** [comment]
Hi Jon,
Thank you for your reply. I tried it more today but unable to install pyfai in my system. It will be great if you can make a simplified version, I have apex 2 installed which can be used to read it. To test it, I can keep 17 hours online if you can help me. Also, I can try it now if you could sent to image you have already converted.
Thank you very much.

**Comment by youthcould** [comment]
Sure. Thanks a lot. guys
