### ISSUE TITLE
Add `python_requires` to setup

### ISSUE THREAD

**Issue by clemisch** [silx-kit/fabio#496]
Please add the required Python version to the setup, such that 

```bash
python3 -m pip install fabio
```

on Python 3.5 installs `fabio==0.10.2` instead of the newest version. Because of dropped 3.5 support, newest fabio can't be imported.

(I know that I can specify the version to install with pip, but including the required Python version directly in the package is easier for the end-user / maintainer of research servers ;-) )

**Comment by kif** [comment]
Thanks for the advice. I will try to ensure the proper versions are used. The packaging system will change for the next release of fabio, probably going away from `setup.py` since we use some features from `numpy` which are now deprecated.
