### ISSUE TITLE
Sparse files written by LIMA2 are not identified.

### ISSUE THREAD

**Issue by kif** [silx-kit/fabio#500]
The "creator" (attribute of the root) is `b'LIMA2'` and not `'LIMA2'`, this is one issue, the second is that there is no way to distinguish a file with a dense stack from a sparse stack ...

**Comment by kif** [comment]
It is straight forward to find '/entry_0000/instrument/Simulator/plot` where the data are actually stored. So +1 to put an attribute there.

We could imagine having an attribute `@dataformat = "sparsify-Bragg"` (it is the name of the program in the pyFAI suite.

**Comment by sdebionne** [comment]
Shall we have `@dataformat = "Dense"` or no attribute at all in the regular case?

**Comment by kif** [comment]
this is the default behaviour ...

**Comment by kif** [comment]
That's how it is done now:
https://github.com/silx-kit/fabio/pull/510/files#diff-4e263713c395eee8793816d0bf5c137d0f53a34f42c4c830dfe5672f137ffdd9
