### ISSUE TITLE
checksum mismatch for small CBF files

### ISSUE THREAD

**Issue by elmjag** [silx-kit/fabio#528]
When loading 'small' CBF files following warning is printed.

    Checksum of binary data mismatch: expected b'EvAj8G5+wSmG8f8KLiYYjg==', got b'oMD7XXKaVM+WCYVKGCQxfQ=='
    
See attached [mismatch.py.txt](https://github.com/silx-kit/fabio/files/11219801/mismatch.py.txt) file for an example.

This problem is only present for CBF files with 'small' data section. When loading 'small' CBF files, fabio calculates wrong MD5 checksum of the data, thus the above message.

For small files, the read size at this line:

https://github.com/silx-kit/fabio/blob/main/fabio/cbfimage.py#L217

become negative. Subsequently the raw data returned here:

https://github.com/silx-kit/fabio/blob/main/fabio/cbfimage.py#L223

will not be correct. The returned bytes will contain the 'data' section _and_ also the trailng part `--CIF-BINARY-FORMAT-SECTION----`. Thus the MD5 sum will be calculated over wrong bytes array.

**Comment by kif** [comment]
Thanks a lot for the report, the regression test and the analysis.
