### ISSUE TITLE
Cannot read cbf images in latest fabio versions

### ISSUE THREAD

**Issue by CPrescher** [silx-kit/fabio#535]
A Dioptas user has opened an issue in the Dioptas repo (https://github.com/Dioptas/Dioptas/issues/151), saying that in the latest versions their CBF images cannot be open anymore. There is an issue with parsing the header of the file.

**Comment by kif** [comment]
@isidrocg thanks for the faulty image ... 
It looks like long path are split on several lines and fabio was not design to support this feature.
