### ISSUE TITLE
WARNING:fabio.TiffIO:Data at tag id '65000' is smaller than expected

### ISSUE THREAD

**Issue by ptorbjorn** [silx-kit/fabio#536]
I have problem reading files from my last experiment, using jupyter notebook on windows computer.
Have fabio version: 2023.4.1
Pythonversion: 3.10.9

When reading [saxsdata=fabio.open('test.tif'] a file I get the following message:
WARNING:fabio.TiffIO:Data at tag id '65000' is smaller than expected

I have attached the file in a "zip-file" since I can not upload the tif file by it self.
[test.zip](https://github.com/silx-kit/fabio/files/11933869/test.zip)

I hope that some one can help me on this issue.

**Comment by kif** [comment]
I don't think this is an issue: the file is read properly. 
@vasole is specialist of Tiff files, maybe he can comment on this and tell us if this is harmful.

**Comment by ptorbjorn** [comment]
Thank you!
We can close this.

**Comment by kif** [comment]
Thanks Armando
