### ISSUE TITLE
which runtime dependencies for fabio

### ISSUE THREAD

**Issue by picca** [silx-kit/fabio#538]
Hello, when packaging I need to add these dependencies in order to run all the unit test

https://sources.debian.org/src/python-fabio/0.14.0+dfsg-2/debian/patches/0002-fix-the-install_requires-depends.patch/

the pyproject.toml declare only the numpy dependencies.

My opinion, is that all the dependencies declar ein the fabio code should be listed in the runtime dependencies.

Cheers

Fred

**Comment by kif** [comment]
I agree, here is a patch to the `pyproject.toml` file which ensures this works:
```
python3 -m venv /tmp/fabio538
source /tmp/fabio538/bin/activate
cd workspace/fabio
pip install .
python run_tests.py  --installed
```
