### ISSUE TITLE
Build issue since moving fabio to src

### ISSUE THREAD

**Issue by blochl** [silx-kit/fabio#546]
Hi,

I package FabIO for Arch Linux, and after commit 8b5d435f3849d361e91ff6dc1d682ef4281494c4 there's a build issue. I can't use pip and virtualenv for packaging, so I just did before:
```
python setup.py build
...
python setup.py install --root="${pkgdir}/" --optimize=1
...
```
Now, when `setup.py` is moved to `src/fabio`, I `cd` there and do `python setup.py build`, and get the following error:
```
/fabio/src/fabio/setup.py:30: DeprecationWarning: 

  `numpy.distutils` is deprecated since NumPy 1.23.0, as a result
  of the deprecation of `distutils` itself. It will be removed for
  Python >= 3.12. For older Python versions it will remain present.
  It is recommended to use `setuptools < 60.0` for those Python versions.
  For more details, see:
    https://numpy.org/devdocs/reference/distutils_status_migration.html 


  from numpy.distutils.misc_util import Configuration
Appending fabio.app configuration to fabio
Ignoring attempt to set 'name' (from 'fabio' to 'fabio.app')
Appending fabio.benchmark configuration to fabio
Ignoring attempt to set 'name' (from 'fabio' to 'fabio.benchmark')
Appending fabio.ext configuration to fabio
Ignoring attempt to set 'name' (from 'fabio' to 'fabio.ext')
Appending fabio.test.codecs configuration to fabio.test
Ignoring attempt to set 'name' (from 'fabio.test' to 'fabio.test.codecs')
Appending fabio.test configuration to fabio
Ignoring attempt to set 'name' (from 'fabio' to 'fabio.test')
Appending fabio.third_party configuration to fabio
Ignoring attempt to set 'name' (from 'fabio' to 'fabio.third_party')
Appending fabio.utils configuration to fabio
Ignoring attempt to set 'name' (from 'fabio' to 'fabio.utils')
Appending fabio.compression configuration to fabio
Ignoring attempt to set 'name' (from 'fabio' to 'fabio.compression')
running build
running config_cc
INFO: unifing config_cc, config, build_clib, build_ext, build commands --compiler options
running config_fc
INFO: unifing config_fc, config, build_clib, build_ext, build commands --fcompiler options
running build_src
INFO: build_src
INFO: building extension "fabio.ext.cf_io" sources
Traceback (most recent call last):
  File "/fabio/src/fabio/setup.py", line 49, in <module>
    setup(configuration=configuration)
  File "/usr/lib/python3.11/site-packages/numpy/distutils/core.py", line 170, in setup
    return old_setup(**new_attr)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.11/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.11/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/usr/lib/python3.11/site-packages/numpy/distutils/command/build.py", line 62, in run
    old_build.run(self)
  File "/usr/lib/python3.11/distutils/command/build.py", line 135, in run
    self.run_command(cmd_name)
  File "/usr/lib/python3.11/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.11/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/usr/lib/python3.11/site-packages/numpy/distutils/command/build_src.py", line 144, in run
    self.build_sources()
  File "/usr/lib/python3.11/site-packages/numpy/distutils/command/build_src.py", line 161, in build_sources
    self.build_extension_sources(ext)
  File "/usr/lib/python3.11/site-packages/numpy/distutils/command/build_src.py", line 324, in build_extension_sources
    sources, py_files = self.filter_py_files(sources)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/numpy/distutils/command/build_src.py", line 391, in filter_py_files
    return self.filter_files(sources, ['.py'])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/numpy/distutils/command/build_src.py", line 400, in filter_files
    (base, ext) = os.path.splitext(source)
                  ^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen posixpath>", line 118, in splitext
TypeError: expected str, bytes or os.PathLike object, not list
```

**Comment by blochl** [comment]
Not an issue. Did not notice the transition to meson.
@kif - can you please document the manual meson installation in http://www.silx.org/doc/fabio/latest/install.html#manual-installation-for-any-operating-system ?

While at it, is the old flag `--optimize=1` still valid? The meson build seems not to have such an option.

**Comment by kif** [comment]
Hi, since python 3.12 is out, the instsllation based on setup.py is no more functionnal (it was relying on numpy.distutils). I am preparing a new release which supports only meson-python. Thanks for reminding me to ensure the docs have been updated.
Until then, you can have a look at the nighly built doc at:
https://www.silx.org/doc/fabio/dev/install.html
Thanks for taking care of the Arch packaging.

**Comment by kif** [comment]
What does this optimize option do?

**Comment by blochl** [comment]
> Hi, since python 3.12 is out, the instsllation based on setup.py is no more functionnal (it was relying on numpy.distutils). I am preparing a new release which supports only meson-python. Thanks for reminding me to ensure the docs have been updated. Until then, you can have a look at the nighly built doc at: https://www.silx.org/doc/fabio/dev/install.html Thanks for taking care of the Arch packaging.

Thanks!

**Comment by blochl** [comment]
> What does this optimize option do?

Here's the doc for the `--optimize=1` option I've used so far: https://setuptools.pypa.io/en/latest/deprecated/distutils/apiref.html#distutils.util.byte_compile

I wonder if meson takes care of it automatically...

**Comment by kif** [comment]
There is optimization at 2 levels:
- When compiling the code, https://github.com/silx-kit/fabio/blob/main/bootstrap.py#L39 where you can specify the debug/plain/release mode (note this is automatically properly handled).
- the byte-compilation of the source python files and I believe, this is performed  by the pip tool which installs files from the wheel.

**Comment by blochl** [comment]
Thanks, all clear, closing the issue, and the package is updated.

@kif - just can you please describe the manual installation method in the doc (without pip, as pip can't always be used). _I.e._:
```
python -m build --wheel --no-isolation
python -m installer dist/*.whl
```
