### ISSUE TITLE
Support for newer GE files?

### ISSUE THREAD

**Issue by psavery** [silx-kit/fabio#553]
Hi there,

First of all, thank you for providing and supporting this great project! We use `fabio` to support many detector file formats in [hexrd](https://github.com/hexrd/hexrd).

For GE files, our users have typically used ge2 files, which seem to work fine with fabio.

Recently, however, some users have tried using ge3 and ge5 files. Correct me if I'm wrong, but ge3 files might already be supported by fabio (the examples I see have a blank header, so I can't tell what the difference might be with ge2). But ge5 appear to have a different header format. Looks like it contains key-value pairs:

```
{EDF_DataBlockID = 1.Image.Psd ; ^M
EDF_HeaderSize =       8192 ; ^M
HeaderID = EH:000001:000000:000000 ; ^M
ByteOrder = LowByteFirst ; ^M
Num_Images = 1441 ; ^M
DataType = UnsignedShort ; ^M
Image = 1 ; ^M
Dim_1 = 2048 ; ^M
Dim_2 = 2048 ; ^M
Size = 8388608 ; ^M
}
```

Are there any existing plans to support ge5 files? We may contribute support for them to fabio, if not.

Thank you!
Patrick

**Comment by jonwright** [comment]
Hello,
What is the error you get using `fabio.open("some_example_file")`? It looks like it should be recognised and read as EDF. I thought the blank headers should also get read as GE [here](https://github.com/silx-kit/fabio/blob/c1eff28cd17f9bacf035fb4b163becc7dba9f971/src/fabio/openimage.py#L84)
Best,
Jon

**Comment by psavery** [comment]
Hi @jonwright! Thanks, that is helpful! Yes, I see now that it is actually reading the ge5 files as EDF.

The actual issue we encountered is that only 1 frame appears to be read in. For my example, though, there are 1441 frames (see `Num_Images` above), but `img.nframes` only reports 1 frame. Do you know why this might be?

I would share my example file with you, but I would need to get permission first.

**Comment by psavery** [comment]
I looked through the fabio code and stepped through it a bit. It looks like fabio is expecting a header for each frame, but this file only contains one header at the beginning of the file. fabio raises this exception when reading the second frame:

```python
fabio.edfimage.MalformedHeaderError: Header frame 1 does not contain '{'
```

Indeed, looking at the raw file, there is only a header at the beginning of the whole file.

Is this file invalid? Or does fabio need to be updated to read this file correctly?

FYI: this file was generated at APS.

**Comment by kif** [comment]
There is probably a bug or smth missing. Could you please share a (small) file to build bug-regression before fixing it. Thanks.

**Comment by jonwright** [comment]
Is `Num_Images = 1441` a new feature? I don't remember seeing that in the past for multi-frame edf.

**Comment by psavery** [comment]
@kif I will see if I can provide an example!

@jonwright Possibly. This dataset was collected in 2022. I wish I had some documentation about the format.

**Comment by jonwright** [comment]
Nowadays ESRF is migrating to hdf5.

The "edf" format stopped being documented about 20 years ago. Probably there was some divergence between the original specification and the files that were produced. You can find a copy of the old format spec via the [waybackmachine](https://web.archive.org/web/20050908164446/http://www.esrf.fr/computing/scientific/data_format/esrf_format.pdf). It does not help you much because the files have diverged from the specification.

**Comment by psavery** [comment]
I received permission to share this dataset with you. Can you provide me your email? You can send it to my email: patrick.avery@kitware.com

**Comment by kif** [comment]
@jonwright :
I searched such a document for ages when taking over FabIO. Recently (2019), a draft of this document from 1993 was found in paper version, but less complete. I guess this document has also to be classified as *deprecated + confidential*. This confirms the divergence between the mainstream implementation and those specifications.
@psavery : The file will be send to http://www.silx.org/pub/fabio/testimages/

**Comment by psavery** [comment]
I only received permission to share this file with the fabio developers (not make it public). Plus, it's 12 GB, so not a good test candidate :slightly_smiling_face:.

I will ask some folks at APS if they can provide me a smaller sample ge5 file. We could use that in the tests if I can get a hold of one.
