### ISSUE TITLE
Using fabio to read detector H5 files other than Eiger (e.g. Lambda, etc)

### ISSUE THREAD

**Issue by lorcat** [silx-kit/fabio#565]
Hi!
I have tried recently to use _fabio_ for an **HDF5/NEXUS** from an **X-spectrum Lambda** multi-module system.

Python 3.12.3
fabio                     2024.4.0        py312ha90f08f_0    conda-forge

>>> fabio.openimage.openimage("l1_test02_00002_master.nxs")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\glazyrin\.conda\envs\latest_fabio\Lib\site-packages\fabio\openimage.py", line 210, in openimage
    obj = obj.read(obj.filename, frame)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\glazyrin\.conda\envs\latest_fabio\Lib\site-packages\fabio\eigerimage.py", line 156, in read
    raise NotGoodReader("HDF5 file does not contain an Eiger-like structure.")
fabio.fabioutils.NotGoodReader: HDF5 file does not contain an Eiger-like structure.

I am interested in using _fabio_ in own code and as a part of [DIOPTAS](https://github.com/Dioptas/Dioptas), including HDF5 [VDS](https://docs.h5py.org/en/stable/vds.html) capability. Do you think it will be possible to add this detector structure to fabio?

The appended files are as follows:
l1_test02_00002_m0[1-3].nxs - correspond to individual modules
l1_test02_00002_master.nxs - The master file with VDS (Virtual Datasets)

[lambda_detector.zip](https://github.com/silx-kit/fabio/files/15106735/lambda_detector.zip)

**Comment by kif** [comment]
This should be possible if there are some headers which allow to distinguish those files from the one generated by lima or dectris.

**Comment by lorcat** [comment]
The structure of these NEXUS files is fairly simple and one can also check it via silx or else viewer.

Here are the pictures illustrating it for the individual module and the master file.
![individual_module_info](https://github.com/silx-kit/fabio/assets/5584235/e83225b7-9879-40ce-9e78-0f79e07f8b6f)
![master_file](https://github.com/silx-kit/fabio/assets/5584235/ce756196-5e5c-48b9-b586-20528662b078)

Hopefully there will be more multimodule lambdas around, I know about 9M with 12 modules under commissioning now. Having the capability with _fabio_ would be great!

**Comment by lorcat** [comment]
yes, it has the "Lambda" string. The master file and the modules files are different by absence of the ../module[0-9]+ branch

**Comment by kif** [comment]
@lorcat : Can you have a look the associated PR to check if it meets your needs ?

**Comment by lorcat** [comment]
Hi! Sorry, what is PR in this case?

**Comment by lorcat** [comment]
Hi! PR=pull request. Sure, what should I do?

**Comment by kif** [comment]
Can you retrieve the PR and install it locally to validate the reading on your files
```
wget https://github.com/kif/fabio/archive/refs/heads/565_lambda.zip
unzip 565_lambda.zip
cd fabio-565_lambda
pip install .
```
and then check it is working for your files...

**Comment by lorcat** [comment]
Hi! 

I have tried the master file and the individual module. So far works, thank you!

`>>> import fabio
>>> fh = fabio.openimage.openimage("l1_test02_00002_master.nxs")
>>> fh.data
array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int16)
>>> fh.data.shape
(1813, 1555)
`

`
>>> fh = fabio.openimage.openimage("l1_test02_00002_m01.nxs")
>>> fh.data.shape
(516, 1554)
>>> fh.data
array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int16)
`

**Comment by lorcat** [comment]
Right, we will have a 2M lambda in 1 week. I will let you know then.
Many thanks!

**Comment by lorcat** [comment]
One thing to mention is that the master file and modules contain 5 frames.

The following code reports only one:

import fabio
fh = fabio.openimage.openimage("l1_test02_00002_master.nxs")
fh.data
array([[0, 0, 0, ..., 0, 0, 0],
[0, 0, 0, ..., 0, 0, 0],
[0, 0, 0, ..., 0, 0, 0],
...,
[0, 0, 0, ..., 0, 0, 0],
[0, 0, 0, ..., 0, 0, 0],
[0, 0, 0, ..., 0, 0, 0]], dtype=int16)
fh.data.shape
(1813, 1555)

**Comment by kif** [comment]
That's the normal behaviour of fabio ... you can access to all frames:
* either using the FabioImage as an iterator,
* or using the getframe method to get access to the frame of your choice.

This all comes from a time when there was no reason to put more then a
single frame per file ... FabIO was started around 2006 !

**Comment by lorcat** [comment]
Hi! I have tested the library and it seem to work ok for now.
FABIO version: 15/03/2024

```
with fabio.openimage.openimage(filename) as data:
    for frame in (100,200,300):
        print(data.getframe(frame).shape, np.sum(data.getframe(frame).data))
```

![frame_01](https://github.com/silx-kit/fabio/assets/5584235/2a862e77-dc26-4f5e-a0f0-d2613014671f)

**Comment by kif** [comment]
Thanks for the feed-back. The code has been merged.
