### ISSUE TITLE
[2024.4.0][s390x] test failures

### ISSUE THREAD

**Issue by picca** [silx-kit/fabio#571]
Hello, here errors reported during the Debian build on s390x architecture
These failures  block the fabio migration.

 little/big endian issue it seems

Cheers

=================================== FAILURES ===================================
__________________________ TestBinaryImage.test_write __________________________

self = <fabio.test.codecs.test_binaryimage.TestBinaryImage testMethod=test_write>

    def test_write(self):
        fn = os.path.join(UtilsTest.tempdir, "binary_write.h5")
        ary = numpy.random.randint(0, 100, size=self.shape)
        e = BinaryImage(data = ary)
        e.save(fn)
        self.assertTrue(os.path.exists(fn), "file exists")
        f = BinaryImage()
        f.read(fn, self.shape[1], self.shape[0], offset=0, bytecode=ary.dtype)
        self.assertEqual(str(f.__class__.__name__), "BinaryImage", "Used the write reader")
        self.assertEqual(self.shape, f.shape, "shape matches")
>       self.assertEqual(abs(f.data - ary).max(), 0, "first frame matches")
E       AssertionError: 7133701809754865565 != 0 : first frame matches

fabio/test/codecs/test_binaryimage.py:81: AssertionError
____________________________ TestMskWrite.testBzip2 ____________________________

self = <fabio.test.codecs.test_fit2dmaskimage.TestMskWrite testMethod=testBzip2>

    def testBzip2(self):
        self.filename = os.path.join(UtilsTest.tempdir, "random.msk.gz")
>       self.atest()

fabio/test/codecs/test_fit2dmaskimage.py:139: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
fabio/test/codecs/test_fit2dmaskimage.py:115: in atest
    r = fabio.open(self.filename)
fabio/openimage.py:210: in openimage
    obj = obj.read(obj.filename, frame)
fabio/fit2dmaskimage.py:82: in read
    self._readheader(fin)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <fabio.fit2dmaskimage.Fit2dMaskImage object at 0x3ffb45b9a10>
infile = fabio.<gzip _io.BufferedReader name='/tmp/fabio_marw7ezy_buildd/random.msk.gz' 0x3ffb46d79a0>

    def _readheader(self, infile):
        """
        Read in a header from an already open file
        """
        # 1024 bytes gives 256x32 bit integers
        header = infile.read(1024)
        for i, j in [(b"M", 0),
                     (b"A", 4),
                     (b"S", 8),
                     (b"K", 12)]:
            if header[j] != i[0]:
                raise Exception("Not a fit2d mask file")
        fit2dhdr = numpy.frombuffer(header, numpy.int32)
        # Enforce little endian
        if not numpy.little_endian:
>           fit2dhdr.byteswap(True)
E           ValueError: array to be byte-swapped is read-only

fabio/fit2dmaskimage.py:71: ValueError
____________________________ TestMskWrite.testFlat _____________________________

self = <fabio.test.codecs.test_fit2dmaskimage.TestMskWrite testMethod=testFlat>

    def testFlat(self):
        self.filename = os.path.join(UtilsTest.tempdir, "random.msk")
>       self.atest()

fabio/test/codecs/test_fit2dmaskimage.py:131: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
fabio/test/codecs/test_fit2dmaskimage.py:115: in atest
    r = fabio.open(self.filename)
fabio/openimage.py:210: in openimage
    obj = obj.read(obj.filename, frame)
fabio/fit2dmaskimage.py:82: in read
    self._readheader(fin)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <fabio.fit2dmaskimage.Fit2dMaskImage object at 0x3ffb40e33d0>
infile = <_io.FileIO name='/tmp/fabio_marw7ezy_buildd/random.msk' mode='rb' closefd=True>

    def _readheader(self, infile):
        """
        Read in a header from an already open file
        """
        # 1024 bytes gives 256x32 bit integers
        header = infile.read(1024)
        for i, j in [(b"M", 0),
                     (b"A", 4),
                     (b"S", 8),
                     (b"K", 12)]:
            if header[j] != i[0]:
                raise Exception("Not a fit2d mask file")
        fit2dhdr = numpy.frombuffer(header, numpy.int32)
        # Enforce little endian
        if not numpy.little_endian:
>           fit2dhdr.byteswap(True)
E           ValueError: array to be byte-swapped is read-only

fabio/fit2dmaskimage.py:71: ValueError
____________________________ TestMskWrite.testGzip _____________________________

self = <fabio.test.codecs.test_fit2dmaskimage.TestMskWrite testMethod=testGzip>

    def testGzip(self):
        self.filename = os.path.join(UtilsTest.tempdir, "random.msk.gz")
>       self.atest()

fabio/test/codecs/test_fit2dmaskimage.py:135: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
fabio/test/codecs/test_fit2dmaskimage.py:115: in atest
    r = fabio.open(self.filename)
fabio/openimage.py:210: in openimage
    obj = obj.read(obj.filename, frame)
fabio/fit2dmaskimage.py:82: in read
    self._readheader(fin)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <fabio.fit2dmaskimage.Fit2dMaskImage object at 0x3ffb4114b10>
infile = fabio.<gzip _io.BufferedReader name='/tmp/fabio_marw7ezy_buildd/random.msk.gz' 0x3ffb453be80>

    def _readheader(self, infile):
        """
        Read in a header from an already open file
        """
        # 1024 bytes gives 256x32 bit integers
        header = infile.read(1024)
        for i, j in [(b"M", 0),
                     (b"A", 4),
                     (b"S", 8),
                     (b"K", 12)]:
            if header[j] != i[0]:
                raise Exception("Not a fit2d mask file")
        fit2dhdr = numpy.frombuffer(header, numpy.int32)
        # Enforce little endian
        if not numpy.little_endian:
>           fit2dhdr.byteswap(True)
E           ValueError: array to be byte-swapped is read-only

fabio/fit2dmaskimage.py:71: ValueError
________________________ TestPixiImage.test_file_series ________________________

self = <fabio.test.codecs.test_pixiimage.TestPixiImage testMethod=test_file_series>

    def test_file_series(self):
>       image = fabio.open(self.file_series)

fabio/test/codecs/test_pixiimage.py:123: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
fabio/openimage.py:210: in openimage
    obj = obj.read(obj.filename, frame)
fabio/pixiimage.py:91: in read
    self._readheader(infile)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <fabio.pixiimage.PixiImage object at 0x3ffb3fa2450>
infile = <_io.FileIO [closed]>

    def _readheader(self, infile):
        infile.seek(0)
        self.header = self.check_header()
        byt = infile.read(4)
        framesize = numpy.frombuffer(byt, numpy.int32)
        if framesize * 2 == self._FRAME_SIZE - self._MAGIC_SIZE:
            self.header['framesize'] = framesize
            self.header['width'] = self._IMAGE_WIDTH
            self.header['height'] = self._IMAGE_HEIGHT
            self.header['offset'] = self._HEADER_SIZE
        else:
            logger.warning("Bad framesize: %s", framesize)
>           raise Exception("Bad framesize")
E           Exception: Bad framesize

fabio/pixiimage.py:82: Exception
------------------------------ Captured log call -------------------------------
WARNING  fabio.pixiimage:pixiimage.py:81 Bad framesize: [179831552]
________________________ TestPixiImage.test_multi_frame ________________________

self = <fabio.test.codecs.test_pixiimage.TestPixiImage testMethod=test_multi_frame>

    def test_multi_frame(self):
>       image = fabio.open(self.multi_frame)

fabio/test/codecs/test_pixiimage.py:107: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
fabio/openimage.py:210: in openimage
    obj = obj.read(obj.filename, frame)
fabio/pixiimage.py:91: in read
    self._readheader(infile)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <fabio.pixiimage.PixiImage object at 0x3ffb3bdc8d0>
infile = <_io.FileIO [closed]>

    def _readheader(self, infile):
        infile.seek(0)
        self.header = self.check_header()
        byt = infile.read(4)
        framesize = numpy.frombuffer(byt, numpy.int32)
        if framesize * 2 == self._FRAME_SIZE - self._MAGIC_SIZE:
            self.header['framesize'] = framesize
            self.header['width'] = self._IMAGE_WIDTH
            self.header['height'] = self._IMAGE_HEIGHT
            self.header['offset'] = self._HEADER_SIZE
        else:
            logger.warning("Bad framesize: %s", framesize)
>           raise Exception("Bad framesize")
E           Exception: Bad framesize

fabio/pixiimage.py:82: Exception
------------------------------ Captured log call -------------------------------
WARNING  fabio.pixiimage:pixiimage.py:81 Bad framesize: [179831552]
_______________________ TestPixiImage.test_single_frame ________________________

self = <fabio.test.codecs.test_pixiimage.TestPixiImage testMethod=test_single_frame>

    def test_single_frame(self):
>       image = fabio.open(self.single_frame)

fabio/test/codecs/test_pixiimage.py:100: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
fabio/openimage.py:210: in openimage
    obj = obj.read(obj.filename, frame)
fabio/pixiimage.py:91: in read
    self._readheader(infile)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <fabio.pixiimage.PixiImage object at 0x3ffb3bd0c50>
infile = <_io.FileIO [closed]>

    def _readheader(self, infile):
        infile.seek(0)
        self.header = self.check_header()
        byt = infile.read(4)
        framesize = numpy.frombuffer(byt, numpy.int32)
        if framesize * 2 == self._FRAME_SIZE - self._MAGIC_SIZE:
            self.header['framesize'] = framesize
            self.header['width'] = self._IMAGE_WIDTH
            self.header['height'] = self._IMAGE_HEIGHT
            self.header['offset'] = self._HEADER_SIZE
        else:
            logger.warning("Bad framesize: %s", framesize)
>           raise Exception("Bad framesize")
E           Exception: Bad framesize

fabio/pixiimage.py:82: Exception
------------------------------ Captured log call -------------------------------
WARNING  fabio.pixiimage:pixiimage.py:81 Bad framesize: [179831552]
_________________ TestUtil.test_compress_decode_field_overflow _________________

self = <fabio.test.test_agi_bitfield.TestUtil testMethod=test_compress_decode_field_overflow>

    def test_compress_decode_field_overflow(self):
        data = np.array([1, 2, 3, 4, 255, 40000, -4, 2], dtype="int32")
        fs = agi_bitfield.get_fieldsize(data)
    
        oft = io.BytesIO()
        cf = agi_bitfield.compress_field(data, fs, oft)
>       self.assertEqual(pack("h", 255) + pack("i", 40000), oft.getvalue())
E       AssertionError: b'\x00\xff\x00\x00\x9c@' != b'\xff\x00@\x9c\x00\x00'

fabio/test/test_agi_bitfield.py:70: AssertionError
________________________ TestCompression.test_full_rand ________________________

self = <fabio.test.test_agi_bitfield.TestCompression testMethod=test_full_rand>

    def test_full_rand(self):
        data = np.random.randint(-256, 500, (256, 256)).astype("int32")
        import time
        t0 = time.perf_counter()
>       compressed = agi_bitfield.compress(data)

fabio/test/test_agi_bitfield.py:170: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

frame = array([[-222,  182, -163, ...,  106, -208, -143],
       [-212, -233,  493, ...,   70,  448,  397],
       [  24,  -85...119],
       [  74,  -28,  339, ...,  318,  433,  379],
       [ -93,  242, -177, ...,   55,  -28,  -32]], dtype=int32)

    def compress(frame):
        """compress a frame using the agi_bitfield algorithm
        :param frame: numpy.ndarray
        :returns bytes
        """
    
        dim = frame.shape
        buffer = BytesIO()
    
        row_start = numpy.zeros(dim[0], dtype=numpy.uint32)
    
        for row_index in range(0, dim[0]):
            row_start[row_index] = buffer.tell()
            _compress_row(frame[row_index], buffer)
    
        data_size = pack("<I", buffer.tell())
    
        if numpy.little_endian:
            buffer.write(row_start.tobytes())
        else:
>           buffer.write(row_start.byteswap.tobytes())
E           AttributeError: 'builtin_function_or_method' object has no attribute 'tobytes'

fabio/compression/agi_bitfield.py:82: AttributeError
_______________________ TestFabioConvert.testSingleFile ________________________

self = <fabio.test.test_fabio_convert.TestFabioConvert testMethod=testSingleFile>

    def testSingleFile(self):
        p = self.subprocessFabioConvert("input/03.edf", "-o=output/03.msk")
        self.logCommunicate(p)
        assert(os.path.exists("output/03.msk"))
>       image = fabio.open("output/03.msk")

fabio/test/test_fabio_convert.py:118: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
fabio/openimage.py:210: in openimage
    obj = obj.read(obj.filename, frame)
fabio/fit2dmaskimage.py:82: in read
    self._readheader(fin)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <fabio.fit2dmaskimage.Fit2dMaskImage object at 0x3ffb3f8c910>
infile = <_io.FileIO name='output/03.msk' mode='rb' closefd=True>

    def _readheader(self, infile):
        """
        Read in a header from an already open file
        """
        # 1024 bytes gives 256x32 bit integers
        header = infile.read(1024)
        for i, j in [(b"M", 0),
                     (b"A", 4),
                     (b"S", 8),
                     (b"K", 12)]:
            if header[j] != i[0]:
                raise Exception("Not a fit2d mask file")
        fit2dhdr = numpy.frombuffer(header, numpy.int32)
        # Enforce little endian
        if not numpy.little_endian:
>           fit2dhdr.byteswap(True)
E           ValueError: array to be byte-swapped is read-only

fabio/fit2dmaskimage.py:71: ValueError
_______________________ TestFailingFiles.test_wrong_dm3 ________________________

self = <fabio.test.test_failing_files.TestFailingFiles testMethod=test_wrong_dm3>

    def test_wrong_dm3(self):
>       self.assertRaises(ValueError, fabio.open, self.bad_dm3_filename)

fabio/test/test_failing_files.py:100: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
fabio/openimage.py:210: in openimage
    obj = obj.read(obj.filename, frame)
fabio/dm3image.py:116: in read
    self._readheader()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

    def _readheader(self):
        self.infile.seek(0)
        file_format = self.readbytes(4, numpy.uint32)[0]  # should be 3
>       assert file_format == 3, 'Wrong file type '
E       AssertionError: Wrong file type

fabio/dm3image.py:98: AssertionError
=============================== warnings summary ===============================
fabio/test/test_fabio_image.py::TestPilImage2::testpil
  /<<PKGBUILDDIR>>/.pybuild/cpython3_3.11_fabio/build/fabio/test/test_fabio_image.py:232: RuntimeWarning: invalid value encountered in cast
    return (numpy.random.random(shape) * sys.maxsize / 10).astype(typ)

fabio/test/test_fabio_image.py::TestPilImage3::testpil
  /<<PKGBUILDDIR>>/.pybuild/cpython3_3.11_fabio/build/fabio/test/test_fabio_image.py:240: RuntimeWarning: invalid value encountered in cast
    return ((numpy.random.random(shape) - 0.5) * sys.maxsize / 10).astype(typ)

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
=========================== short test summary info ============================

**Comment by kif** [comment]
Do you know where I could test this code ? Is there an S390 computer available anywhere ? can it be emulated ?
