### ISSUE TITLE
Different import version sources

### ISSUE THREAD

**Issue by poautran** [silx-kit/fabio#573]
Seems like there are 2 different ways to get the version.

`from .._version import version as fabio_version` seems to be problematic.

Found here:
https://github.com/silx-kit/fabio/blob/66d472199a8d09ea23c6fd5a661f850833be5aa7/src/fabio/app/eiger2crysalis.py#L58
https://github.com/silx-kit/fabio/blob/66d472199a8d09ea23c6fd5a661f850833be5aa7/src/fabio/app/densify.py#L57

Different call:
https://github.com/silx-kit/fabio/blob/66d472199a8d09ea23c6fd5a661f850833be5aa7/src/fabio/app/eiger2cbf.py#L52

**Comment by kif** [comment]
What is the issue ? Can you provide the stack-trace ?

**Comment by poautran** [comment]
On `fabio-2024.4.0`
```
>>> from fabio.app.eiger2crysalis import Converter
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/esrf/pautran/venv/ewoksscxrd/lib/python3.8/site-packages/fabio/app/eiger2crysalis.py", line 58, in <module>
    from .._version import version as fabio_version
ModuleNotFoundError: No module named 'fabio._version'
```
