### ISSUE TITLE
EDFImage.fast_read_data: cannot read a line ?

### ISSUE THREAD

**Issue by payno** [silx-kit/fabio#578]
For a specific use case I want to read a specific column or a specific line of an EDF file.

[`EDFImage.fast_read_roi`](https://github.com/silx-kit/fabio/blob/main/src/fabio/edfimage.py#L1337) seems to have the API for it.

In my use case it works for column but I cannot make it work for lines.

But looking at the implementation it looks like this use case might not be handled. For example [L1358](https://github.com/silx-kit/fabio/blob/main/src/fabio/edfimage.py#L1358) and [L 1370](https://github.com/silx-kit/fabio/blob/main/src/fabio/edfimage.py#L1370) it looks like reading is handled over a specific dimension.

Can you confirm or provide me an example on how to call it for lines ?
Else do you think the use case of 'reading specific line(s)' is relevant ? Or would it be as fast to read the full file directly and subset the line of interest ?

Many thanks,

**Comment by jonwright** [comment]
The error is probably the FIXME on line 183 in fabioimage.py make_slice?

**Comment by payno** [comment]
thanks for the quick answer,

I don't think so because I run in this 'limitation' but then I provide `coord` as a tuple of slice. And this is where the shape of the data read  is incoherent (for example on the two lines [L1358](https://github.com/silx-kit/fabio/blob/main/src/fabio/edfimage.py#L1358) and [L 1370](https://github.com/silx-kit/fabio/blob/main/src/fabio/edfimage.py#L1370)).

But maybe this is related and this use case doesn't make much sense at the end.

**Comment by jonwright** [comment]
Maybe it depends on the ROI and image size? Using an mmap might be worth testing. It seemed to help for a simple test case:

```
def read_mmap( self, fname, coords ):
    if len(coords) == 4:
            slice1 = self.make_slice(coords)   # and fix that FIXME ... 
    elif (len(coords) == 2 and 
          isinstance(coords[0], slice) and
          isinstance(coords[1], slice)):
        slice1 = coords
    else:
        logger.warning('readROI: Unable to understand Region Of Interest: got %s', coords)
        return
    with open(fname, 'rb') as fin:
        fin.seek( 0 )
        count = self.shape[0] * self.shape[1]           
        offset = self._frames[self.currentframe].start
        nbytes = self.bpp * count
        with mmap.mmap( fin.fileno(), 
                        offset + nbytes, 
                        access=mmap.ACCESS_READ ) as mem:
            buf = numpy.frombuffer( mem,
                                    offset = offset, 
                                    count = count,
                                    dtype = self.bytecode )
            buf.shape = self.shape
            ret = buf[slice1].copy()
            del buf
    if self.swap_needed():
        ret.byteswap(True)
    return ret
```

**Comment by payno** [comment]
Indeed it seems to work thanks.

By the way I couldn't fine this function anywhere in fabio. Do you know if it is 'normal' or if I miss it somehow ?

**Comment by jonwright** [comment]
That is normal. If it works we could talk to @kif about adding it to fabio. Supporting windows+mac often leads to complications. Maybe preadv is good enough nowadays - it only appeared quite recently. The code comes from something I looked at a couple of years ago to read rows from hdf5. A gist is here:

https://gist.github.com/jonwright/efcbad11d55b92ea904179083b6842a0

**Comment by kif** [comment]
Hi Henri, It should work for lines as well ... 
This is a bug. Can you provide me with a regression test ? I will try to address it.

**Comment by payno** [comment]
Hi Jerome, the following will raise the error I had (initialization might not be straighforward but  at least you should be able to reproduce):

```python
import numpy
import fabio
from fabio.edfimage import EdfImage

file_name = "test.edf"
# create some dummy data
edf_writer = fabio.edfimage.EdfImage(
    data=numpy.arange(0, 100).reshape(10, 10),
)
edf_writer.write(file_name)

edf_reader = fabio.edfimage.EdfImage()
# works
frame_full = edf_reader.read(file_name).data

# if I want to read it line by line
line_index_to_read = 4
line_data = edf_reader.fast_read_roi(
    file_name,coords=(
        slice(0, 10),
        slice(line_index_to_read, line_index_to_read+1),
    ),
)
```

And the error I have is:
```bash
  File "/home/payno/Documents/dev/tomography/test_read_line.py", line 18, in <module>
    line_data = edf_reader.fast_read_roi(
                ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/payno/.local/share/virtualenvs/tomwer_venv_silx_2/lib/python3.11/site-packages/fabio/edfimage.py", line 1375, in fast_read_roi
    return data[slice2]
           ~~~~^^^^^^^^
```

**Comment by payno** [comment]
And we discuss it a bit here if you want: https://gitlab.esrf.fr/tomotools/tomoscan/-/merge_requests/220

**Comment by kif** [comment]
The error is rather in the `slice(0, 10)`, i.e. the whole column.
