### ISSUE TITLE
Documentation not accessible

### ISSUE THREAD

**Issue by jbhopkins** [silx-kit/fabio#583]
The documentation here: http://www.silx.org/doc/fabio/latest/

Will not load in either chrome or firefox for me. Right now it either times out or I get an unsafe site message and can't override it to proceed. I'm assuming this has to do with it being http rather than https. Can you update to https? Or make sure the documentation on readthedocs (which is accessible and is https) is up to date with the latest version? Right now readthedocs seems to be at 2023.06 (https://fabio.readthedocs.io/en/main/Changelog.html)

**Comment by kif** [comment]
Thanks for the comment, RTD is no more triggered by the CI ! This is actually a bug.

**Comment by pierrepaleo** [comment]
Updated the web server configuration to redirect http to https. Can you give it a try ?

**Comment by kif** [comment]
Looks fixed ...

**Comment by kif** [comment]
RTD is integrated back in CI

**Comment by jbhopkins** [comment]
Thanks for taking a look at things so quickly! I'm still getting a warning about the certificate not being valid, though I can now get to the site.
<img width="534" alt="Screenshot 2024-08-27 at 12 51 41 PM" src="https://github.com/user-attachments/assets/ba0c82bc-0409-4fe3-b692-048f309f5ad0">

**Comment by pierrepaleo** [comment]
I just tested with 
  - Firefox and chromium (Linux) 
  - Firefox, edge (Windows)
It seems to work, at least for what the certificate itself is concerned. But I might have to test on more environments.

Perhaps your operating system is not configured to accept these letsencrypt certificates ?

**Comment by jbhopkins** [comment]
If it helps, I see this in Safari and Chrome on MacOS (14.6.1) but not in Firefox.
