### ISSUE TITLE
32bit Dectris Eiger Tif image not readable

### ISSUE THREAD

**Issue by Luindil** [silx-kit/fabio#72]
Hi,

a Dioptas user contacted me about a tif file which he cannot open. I have the image attached. Fabio and PIL cannot handle the image. I suppose it is because of usage of 32bit UINT and not 32 bit INT.

Do you maybe have a solution for this. I think there will be more and more Eiger images, so I guess this will become a common problem.

[test.tif.zip](https://github.com/silx-kit/fabio/files/526871/test.tif.zip)

**Comment by vallsv** [comment]
Hi. It looks to have a BitsPerSample=64.

**Comment by vallsv** [comment]
It looks to contains a malformed value in tagID 65000. But it can be a problem on our parser. Iv got a fix, i will ask Jerome.

**Comment by Luindil** [comment]
Hi,

thank you for looking into this. But it does still not work for me. When I try to do fabio.open("test.tif") I get the following error:

WARNING:fabio.TiffIO:Data at tag id '65000' is smaller than expected
WARNING:tifimage:Unable to read test.tif with TiffIO due to can't concat bytes to str, trying PIL
ERROR:tifimage:Error in opening test.tif  with PIL

This is on Anaconda Python 3.5 Linux Distribution...

**Comment by vallsv** [comment]
By bad in the patch then, i try with Python 3.4, but i guess not with 3.5

**Comment by Luindil** [comment]
i just tested on anaconda python 3.4 and I get the same error as above, so it is not a python version problem. Maybe libtiff version? I am using 4.0.6-2. Which one are you using?

**Comment by vallsv** [comment]
The patch is not right, anyway

**Comment by vallsv** [comment]
Hi Clemens. Jerome have merged the patch. Can you try the master again?

**Comment by Luindil** [comment]
Thank you, it works now!

**Comment by vallsv** [comment]
You are welcome

**Comment by nguyen14ck** [comment]
Hi Vallsv,

I got this problem when reading the tif file:
Ubuntu 19.04
Python 3.7
Fabio 0.90

```
Number of files: 1
Data at tag id '65006' is smaller than expected
Data at tag id '65007' is smaller than expected
Data at tag id '65009' is smaller than expected
Data at tag id '65010' is smaller than expected
Data at tag id '65024' is smaller than expected
Data at tag id '65025' is smaller than expected
Third dimension is the color
```
Could you look at it? Thanks.

**Comment by vallsv** [comment]
Hi. Could you please open a new issue? And upload a sample that we can use to reproduce the problem?
