### ISSUE TITLE
[debian9] future deprecation warning

### ISSUE THREAD

**Issue by kif** [silx-kit/fabio#82]
There a 4 warning when running the tests under debian-9 + python 3.5:
apparently fabio does file.read(size) where size is (sometimes) a numpy array with one element.

**Comment by kif** [comment]
The easiest to debug is probably speimage, the other issues are in *bzip2* and *gz* modules.
Clemens, you may be interested ... @Luindil

**Comment by Luindil** [comment]
Hi, I made a pull request to fix the speimage issue
