### ISSUE TITLE
bug in fabio/python3

### ISSUE THREAD

**Issue by marcocamma** [silx-kit/fabio#89]
I have issues opening a OXDimage when running python 3. The image  can be found here: https://cloud.ipr.univ-rennes1.fr/index.php/s/42lAgsOf3vGYnZo.

I used the following code (saved as script  fabio_py2_vs_py3.py):

    from __future__ import print_function
    import sys
    import fabio

    pyv = sys.version_info
    print("Python version: %d.%d.%d"% (pyv.major,pyv.minor,pyv.micro))
    print("Fabio version : %s"%fabio.version)

    fname = '100nmfilmonglass_1_1.img'

    img = fabio.open(fname)
    print("Image %s read successfully" % fname)

When running with python2 I get:

> marco@x1/tmp> python2 fabio_py2_vs_py3.py 
> Python version: 2.7.12
> Fabio version : 0.4.0
> WARNING:OXDimage:# Compressed with the TY5 compression
> Exception encountered: 2:2844, 4:0
> Image 100nmfilmonglass_1_1.img read successfully

when using python3:

> Python version: 3.5.2
> Fabio version : 0.4.0
> WARNING:OXDimage:# Compressed with the TY5 compression
> Traceback (most recent call last):
>   File "fabio_py2_vs_py3.py", line 11, in <module>
>     img = fabio.open(fname)
>   File "/usr/lib/python3/dist-packages/fabio/openimage.py", line 154, in openimage
>     obj = obj.read(obj.filename, frame)
>   File "/usr/lib/python3/dist-packages/fabio/OXDimage.py", line 265, in read
>     self.blob = raw8 + self.raw16 + self.raw32 + self.rest
> TypeError: can't concat bytes to str

it seems to be related to the different way python2 and python3 treats string.
In fact - at least when reading the test image I used - the self.raw32 variable is a string (empty) while everything else is a bytesarray object. A possible solution could be to change `self.raw32` with `bytes(self.raw32,encoding='utf-8')` but I am not sure about all consequences.

Thanks very much in advance for your help,
marco

**Comment by kif** [comment]
Well spotted. Thanks Marco.
We will fix it.
