### ISSUE TITLE
How to convert .img file from ADSC detector to .tif or .edf format?

### ISSUE THREAD

**Issue by sanmaiti2009** [silx-kit/fabio#99]
Hi,
I could convert .img file from ADSC detector to .h5 file by FabIO very easily. But I could not able convert it into .tif/.edf file. Please let me know how to do it. 
Thanks in advance.
Santanu

**Comment by kif** [comment]
On Thu, 19 Jan 2017 08:08:30 -0800
sanmaiti2009 <notifications@github.com> wrote:

> Hi,
> I could to convert .img file from ADSC detector to .h5 file by FabIO very easily. But I could not able convert it into .tif/.edf file. Please let me know how to do it. 
> Thanks in advance.
> Santanu

Hi Santanu,

Did you know about "fabio-convert" ?
I am sorry we did not document about this tool in the official documentation, we will fix it for the next release.

did you try:
fabio-convert -F tif -o image.tif image.img
fabio-convert -F edf -o image.edf image.img

Here is the help of the tool:

$ fabio-convert --help
usage: fabio-convert [-h] [-V] [-v] [--debug] [-l] [-o OUTPUT] [-F FORMAT]
                     [-f] [-n] [--remove-destination] [-u] [-i] [--dry-run]
                     [IMAGE [IMAGE ...]]

FabIO-convert is a portable image converter based on FabIO library.

positional arguments:
  IMAGE                 Input file images

optional arguments:
  -h, --help            show this help message and exit
  -V, --version         output version and exit
  -v, --verbose         show information for each conversions
  --debug               show debug information

main arguments:
  -l, --list            show the list of available formats and exit
  -o OUTPUT, --output OUTPUT
                        output file or directory
  -F FORMAT, --output-format FORMAT
                        output format

optional behaviour arguments:
  -f, --force           if an existing destination file cannot be opened,
                        remove it and try again (this option is ignored when
                        the -n option is also used)
  -n, --no-clobber      do not overwrite an existing file (this option is
                        ignored when the -i option is also used)
  --remove-destination  remove each existing destination file before
                        attempting to open it (contrast with --force)
  -u, --update          copy only when the SOURCE file is newer than the
                        destination file or when the destination file is
                        missing
  -i, --interactive     prompt before overwrite (overrides a previous -n
                        option)
  --dry-run             do everything except modifying the file system

return codes: 0 means a success. 1 means the conversion contains a failure, 2
means there was an error in the arguments

Cheers,

Jerome

**Comment by sanmaiti2009** [comment]
Dear Jerome,

Thanks for your kind information.
I have downloaded fabio-master in my windows 7 desktop.
The file fabio-master/scripts/fabio_viewer.py is a GUI. Importing .img image and convertion into .h5 farmat is possible from this GUI.
If I try to run fabio-master/scripts/fabio-convert.py...It shows "ERROR:fabio-convert:No input file specified ....... Process finished with exit code 2"  Also there is no GUI...Where do I put input file in the script? 
Please let me know.
best regards,
Santanu

**Comment by vallsv** [comment]
Hi.

`fabi-convert` is a script. You have to open a console and type the command line Jerome provides to you:
```
fabio-convert -F tif -o the_new__converted_image.tif your_input_image.img
fabio-convert -F edf -o the_new__converted_image.edf your_input_image.img
```
AFAIK, we do not plan to create a GUI for that use case.

**Comment by kif** [comment]
Indeed, the GUI, fabio-viewer is likely to disappear in a near future, replaced by an equivalent tool provided by silx itself. FabIO would then become (again) a pure library.

@vallsv : Mind that under windows, scripts keep their ".py" extension, so the name of the script should be: fabio-convert.py

**Comment by sanmaiti2009** [comment]
Hi Kif,
Thanks for your reply..
I tried the command it in windows 7 in cmd.exe console..But it does not work !!!
